### ISSUE TITLE
Improve the sidebar at lower resolutions

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#1003]
### Description

> At lower resolutions - 1024 x 768, for example - the left-hand pane shows only icons; however, when you click it, it extends to full length, revealing the names of the folders, etc. This is very annoying, as it does not shrink back down in size automatically (you have to click on the screen somewhere). Can you have a setting to choose "icons only", so it remains a fixed width?

### Expected behavior

Improve the sidebar at lower resolutions. Ideas: 

- Expand and collapse automatically.
- Add a button to manually expand or collapse.
- Keep it always fixed 'icons only'.

**Comment by happyman125** [comment]
@The-Hidden-Hand If we have "icons only" setting, it is implemented on all size of width?
also, if we set "icons only" as true, we can't see folder names anymore?

**Comment by happyman125** [comment]
https://codepen.io/JFarrow/pen/fFrpg
How about this implementation?

**Comment by The-Hidden-Hand** [comment]
@happyman125 
I like, it would improve the UX as the customer suggested.

**Comment by The-Hidden-Hand** [comment]
@happyman125 
Good job on this. Now I feel one detail for being perfect is replacing the 'Menu' icon with CTemplar's logo. Perhaps including the long text version when expanded, up to your taste. What do you think?

![image](https://user-images.githubusercontent.com/45569116/107380725-0abb4700-6ae6-11eb-97b8-02c489acdd17.png)

**Comment by The-Hidden-Hand** [comment]
@happyman125 
There are other issues in the same part you've been working, did you notice them?

- [ ] Text overlaps icon
- [ ] Menu button doesn't work
- [ ] Unread folder is misaligned
![image](https://user-images.githubusercontent.com/45569116/108229329-9d3b9600-7137-11eb-8bc1-5a565837e584.png)

- [ ] When the sidebar is collapsed I can partially see the notification number
![image](https://user-images.githubusercontent.com/45569116/108229639-e4c22200-7137-11eb-97fb-1a4d2e9bc792.png)

- [ ] Notification icons lose the original style, now they are red, small, and misaligned
![image](https://user-images.githubusercontent.com/45569116/108229921-23f07300-7138-11eb-9e4a-3d10653b2623.png)

**Comment by happyman125** [comment]
@The-Hidden-Hand which environment did you test on?(window width, etc).
When doesn't "Menu button" work?

**Comment by The-Hidden-Hand** [comment]
@happyman125 
Firefox. I noticed it doesn't happen with fresh reload, but you have to resize the width while the sidebar is open, and it crashes at some point (with different results, I got another glitch where the sidebar moved to the right side in mobile size). It won't happen many times, I guess, so you decide how worth it to fix.

**Comment by The-Hidden-Hand** [comment]
@happyman125 
Well done.
