### ISSUE TITLE
Unable to move messages back to a system default folder

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#1004]
### Your environment

Any.

### Description

> I accidentally moved some "sent" e-mails into my inbox, but there was no option to move them back - or to any of the other "system" folders - only to user-created ones!

### Expected behavior

I can move emails between folders.

### Actual behavior

System folders are not available and I cannot move messages back.

**Comment by happyman125** [comment]
@The-Hidden-Hand you want to move emails between any folders? I think there is some restriction to implement it. For example, I think Inbox->Sent feature is not existing on gmail as well, but not sure why.

**Comment by The-Hidden-Hand** [comment]
@happyman125 
Traditionally in emails, you can move messages from and to any folder. We will support IMAP-like workflow soon, and we shouldn't restrict messages movement between folders like the user commented, from Inbox to Sent.

**Comment by happyman125** [comment]
@The-Hidden-Hand Let's confirm again. we really disable limitation between folders? If so, you think there also should be features like Inbox->Outbox, Inbox->Draft, etc?

**Comment by superdev0714** [comment]
We have restriction for moving emails between folders on the backend too afaik.
https://github.com/CTemplar/backend/blob/53048d5de26fab1489cdbfc47a8025ebe1b9eab3/app/emails/viewsets.py#L1021-L1027

@The-Hidden-Hand , can you explain why we should allow all to move any to any folders, actually I don't understand.

**Comment by The-Hidden-Hand** [comment]
@CTemplar/front-end 
This limitation doesn't exist in traditional email clients using standard protocols like IMAP. We are going to enable IMAP soon, and the webclient must behave in a way compatible with IMAP, where emails can move to/from any folder.

The issue came now when a user was able to move from Sent folder to Inbox, but cannot move the other way around. By the way and because soon we'll serve emails from IMAP (and also from the database like now) this limitation will break the basic functionality, I think the right choice is to disable this limitation now and be prepared for the future.
