### ISSUE TITLE
Login page will only grow in height but not shrink

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#1034]
https://github.com/CTemplar/webclient/blob/38d5ee714ef58f06e4e5df07d32432cd3a350ce0/src/app/app.component.ts#L83-L95

The following solution only allows growing the window, but not shrinking. I continue suggesting a pure CSS solution if possible.

**Comment by happyman125** [comment]
@The-Hidden-Hand so what do you want exactly about shrinking?

**Comment by The-Hidden-Hand** [comment]
@happyman125 
Paul's friend did an audit and this was one of the points:

> 2. There is a layout issue with background growing in height on the Login page when user typed in fields and got errors.
> 
> Could be easily solved by:
> 
> - allocating a fixed space for errors under the fields even when there're no errors
> - using visibility CSS property
> - making input wrappers and positioning errors absolutely

**Comment by happyman125** [comment]
@The-Hidden-Hand I can't reproduce above issue. You can request screenshot from him?

**Comment by The-Hidden-Hand** [comment]
@happyman125 
I can reproduce. Just start with a small screen, then load the page, resize up, resize down. In the last step, you can notice the page height is fixed at the biggest size you set before.

**Comment by happyman125** [comment]
@The-Hidden-Hand I am sorry I couldn't implement with pure CSS. I tried pure CSS solution as you requested but it is difficult as we need dynamic height based on window height. So I fixed this issue on ts file.

**Comment by The-Hidden-Hand** [comment]
@happyman125 
Any update on this? It behaves very very bad as seen in the video. Otherwise, I would have to revert the merge.

https://user-images.githubusercontent.com/45569116/111995817-4566c500-8b11-11eb-94d9-97864c903b18.mp4

**Comment by The-Hidden-Hand** [comment]
@happyman125 
https://user-images.githubusercontent.com/45569116/111997682-3123c780-8b13-11eb-8305-95dcafcd76d0.mp4

**Comment by happyman125** [comment]
Ok, for now, you can revert it. I couldn't reproduce 2000px height so it has some difficulty and will take some time.

**Comment by The-Hidden-Hand** [comment]
It works perfectly now.
