### ISSUE TITLE
Missing error string on wrong invitation code

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#1074]
### Actual behavior

A customer reported the following:

![Error1](https://user-images.githubusercontent.com/45569116/111114114-b418b100-855a-11eb-8bf4-303ef7145bf1.png)
![error2](https://user-images.githubusercontent.com/45569116/111114118-b549de00-855a-11eb-8fcf-fe6b3d12d78c.png)

**Comment by Raiders0786** [comment]
Hello Hidden hand!

Chirag here , the reporter :)

**Comment by happyman125** [comment]
@Raiders0786 when did you catch above issue? Could you let me know the steps of reproduction?

**Comment by Raiders0786** [comment]
hello @happyman125 

I was Checking in Signup form that day in  the website & I was Trying the XSS Payloads & What we can Insert invite Code Box.
So the Steps to Reproduce is :
1) Visit to https://mail.ctemplar.com/create-account?plan=FREE
2) Fill the details.
3) On Invitation Code Box Enter the payloads:
"<script>alert(1)</script>"@example.com
${class.getClassLoader()}

And You will see that the application is throwing the error {object Object}

hence there are some missing strings for these errors.

Thanks & Regards
@Raiders0786

**Comment by Raiders0786** [comment]
Hi @happyman125 ,

Thank you for patching these Vulnerability, 

Waiting for your reply.

Regards
@Raiders0786
