### ISSUE TITLE
no referrer for clicking links

### ISSUE THREAD

**Issue by ckorder** [CTemplar/webclient#1078]
<a target="_blank" **rel="noopener noreferrer"**
Add to every html link generated within the webclient. 

https://web.dev/external-anchors-use-rel-noopener/

Thanks for considering.

**Comment by The-Hidden-Hand** [comment]
Dear @ckorder ,

Thanks for your suggestion. We already have this changes in the testing branch and we expect to release along this week.

Please, let us know of any other improvement you would like to see and we'll do our best to implement it.

Related: #976
