### ISSUE TITLE
Allow adding contact from different sections

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#1087]
### Expected behavior

The following area should offer an icon/action to add the addresses to an existing or new contact:

![image](https://user-images.githubusercontent.com/45569116/111984774-ba330280-8b03-11eb-9ff3-7511ca6036b8.png)

When composing, the dropdown should show an option for adding the unknown addresses to contacts as an option:

![image](https://user-images.githubusercontent.com/45569116/111984996-fbc3ad80-8b03-11eb-9938-664ef62a601e.png)

Pending improvements:

- [x] Work with encrypted contacts.
- [x] Sometimes it doesn't show the display name (mine from sent emails?).
- [x] More options like whitelist or blacklist?

**Comment by rock-ejin** [comment]
@The-Hidden-Hand , @superdev0714 
I investigated encrypting, decrypting in contacts.
there are 2 ways to work with encrypted contacts.
1. add option to decrypt all contacts on the popover, but i am wondering how and where to show the progress or loading indicator.
2. notify kindly to decrypt contacts on contact page to the user

**Comment by The-Hidden-Hand** [comment]
@rock-ejin 
I think contacts (and other data) should be decrypted in the background for building a ready-to-use store, and the webapp becomes more responsive and probably simpler, avoiding all post-processing and other hooks. ECC keys would speed up decryption times too.

Thoughts?

**Comment by rock-ejin** [comment]
@The-Hidden-Hand 
Contact is decrypted in the background at the loading app, I thought wrong.
I can not fully figure out about ECC key, but the document says it is super fast.
