### ISSUE TITLE
Unable to reply Github emails

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#1089]
### Your environment

Firefox.

### Steps to reproduce

1. Check any email received from Github, like an issue or PR.
2. Reply to it.

### Expected behavior

I'm able to reply to follow-up threads.

### Actual behavior

It is loading with a glitched recipient and blank content.

![image](https://user-images.githubusercontent.com/45569116/112056172-a0b7a800-8b4f-11eb-9128-aa1a328c450e.png)

**Comment by happyman125** [comment]
@The-Hidden-Hand I just reproduced to reply to github email(noreply@github.com) and it works well.
I checked your screenshot and seems like there are some issues on receiver emails on this screen.
To check this more, I will need your email credentials if possible. Or how can I receive such above emails?

**Comment by The-Hidden-Hand** [comment]
@happyman125 
I'm unable to reply to any Github email but I can reply to others :thinking: 

Btw, the Reply-To address for Github notification emails is not noreply@github.com as you got, but it is something like `CTemplar/webclient <reply+AJIUJH4VFIUHP3HHCLOECTF6N47MLEVBNHHDEXDRPE@reply.github.com>`, please check the email headers and make sure replies go to the intended recipients.

There is an issue around there, and likely two. Please take a deeper look.

**Comment by The-Hidden-Hand** [comment]
@rock-ejin 
I believe you didn't test Github replies after patching. I tried and now and the issue is different. It doesn't work because the recipient address is forced all lowercase, and I guess Github is case sensitive.
 
![image](https://user-images.githubusercontent.com/45569116/113685501-da42f400-96b5-11eb-99a3-08df62d5358c.png)

![image](https://user-images.githubusercontent.com/45569116/113685606-f5156880-96b5-11eb-9f8b-9e3b472ea854.png)

**Comment by The-Hidden-Hand** [comment]
The recipients' field in the reply composer window is still taking a bit longer than I would expect with the spinner animation. I'm unsure if there is something wrong behind it.

**Comment by rock-ejin** [comment]
I just used pipe, so it will not update the pure email, but i see forcing change to lowercase from the original source.

**Comment by rock-ejin** [comment]
> The recipients' field in the reply composer window is still taking a bit longer than I would expect with the spinner animation. I'm unsure if there is something wrong with it.

ngx-chip has static maximum width for the tag internally.
this is what i truncated the email address like gmail.
please make sure i should make it less width or what.

**Comment by The-Hidden-Hand** [comment]
@rock-ejin 
Not sure if we are talking about the same issue.
Could we stop forcing lowercase recipients, at least for Reply-To addresses?

I'm not aware of any side effects, as per standards, but I think @superdev0714 may have done that for a reason in our codebase, not sure.

**Comment by The-Hidden-Hand** [comment]
Incoming > Case insensitive
Outgoing > Case sensitive

**Comment by rock-ejin** [comment]
ok, let me do it.

**Comment by rock-ejin** [comment]
forcing lowercase is not done on the frontend, backend doing it.
what the frontend doing is just confirmation, means the reply-to is forced changed to lowercase.

**Comment by The-Hidden-Hand** [comment]
@rock-ejin @nitishkansal 
Ok, I thought it was frontend lowercasing addresses.

The issue is when I want to reply, as seen in the images above, the Reply-To address from Github contains uppercase characters while the address is forced lowercase, then the replies never reach the expected workflow.

**Comment by nitishkansal** [comment]
This is fixed, I am not enforcing case sensitivity on reply-to emails now and storing them as it is.
