### ISSUE TITLE
Remote encrypted link to CTemplar user will fail

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#1106]
### Your environment

Firefox.

### Steps to reproduce

1. Send a remote encrypted link (I did from one alias to another alias within my account)
2. The message will loop forever

### Expected behavior

It should also work for CTemplar users because I can generate links to share. It can help to spread the CTemplar word.

An alternative is to don't allow sending these to myself, but allow me to generate a shareable link (?).

**Comment by happyman125** [comment]
@The-Hidden-Hand how do we send "remote encrypted link"?

**Comment by The-Hidden-Hand** [comment]
@happyman125 
From the composer, the tooltip says "Encrypt for non-CTemplar users"

![image](https://user-images.githubusercontent.com/45569116/113053059-6a090f80-9197-11eb-8e95-d14d6849463e.png)
