### ISSUE TITLE
Use CTemplar logo as app icon

### ISSUE THREAD

**Issue by mrusme** [CTemplar/webclient#1116]
### Expected behavior

Please make use of the [official CTemplar logo](https://ctemplar.com/wp-content/themes/ctemplar/assets/img/mediakit-logo-00.svg) as app icon for the Electron app.

**Comment by The-Hidden-Hand** [comment]
Duplicated: #964

**Comment by mrusme** [comment]
<img width="790" alt="Screen Shot 2021-05-14 at 5 37 57 PM" src="https://user-images.githubusercontent.com/151967/118338261-4e559080-b4db-11eb-8548-181f717b23f5.png">

It's **glorious**!
