### ISSUE TITLE
Configurable hard wrap for plain text mails

### ISSUE THREAD

**Issue by mrusme** [CTemplar/webclient#1117]
It would be super nice if the mail editor would allow for configurable (in terms of line length) hard wraps when composing plain text mails.

**Comment by The-Hidden-Hand** [comment]
The default would be 80 characters.

**Comment by The-Hidden-Hand** [comment]
Related: https://github.com/CTemplar/support/issues/130

**Comment by The-Hidden-Hand** [comment]
It's done @mrusme :)
Let us know if you feel it can improve.
