### ISSUE TITLE
Fixed-width font for mail editor / mail viewer

### ISSUE THREAD

**Issue by mrusme** [CTemplar/webclient#1118]
CTemplar current allows to change the `Default composing font` in its `General` settings. Unfortunately there's no fixed-width font available. It would be nice to have a couple of them (e.g. [Fira Code](https://github.com/tonsky/FiraCode), [Roboto Mono](https://github.com/googlefonts/RobotoMono), [Source Code Pro](https://github.com/adobe-fonts/source-code-pro), ...) to pick from. Also it would be cool if they would also apply to the mail viewer and not only to the editor/composer.

**Comment by The-Hidden-Hand** [comment]
We have added Monospace for now.

We'll be adding more fonts, including some for accessibility and custom themes in the near future.

Please let us know if you have any other suggestion @mrusme.
