### ISSUE TITLE
Print doesn't work on Electron apps

### ISSUE THREAD

**Issue by mrusme** [CTemplar/webclient#1119]
### Your environment

macOS, CTemplar Electron app

### Steps to reproduce

Open a (plain text) e-mail and try to print it.

### Expected behavior

The printer dialog showing up. Or a print-rendered document in a new window so one can Cmd/Ctrl+P it.

### Actual behavior

![print](https://user-images.githubusercontent.com/151967/113303436-b4d57500-92c6-11eb-861f-3dd3f9a84406.gif)

**Comment by The-Hidden-Hand** [comment]
@mrusme 
Looks like it was only solved for Windows, but not Linux, could you tell me what about macOS?
The printing function seems a bit special not working everywhere.

**Comment by mrusme** [comment]
Works perfectly fine now! 👍🏼

**Comment by The-Hidden-Hand** [comment]
@superdev0714 
Recurring issue. I'm unable to print again on the Linux Desktop App.
There isn't Control+P and the dropdown action is not working too.

**Comment by rock-ejin** [comment]
I checked the print function on the Linux desktop app. It is working after fixed #support-203.
But Control+P is not working on Windows and Linux now.

**Comment by The-Hidden-Hand** [comment]
> I checked the print function on the Linux desktop app. It is working after fixed #support-203.
> But Control+P is not working on Windows and Linux now.

@rock-ejin 
It works on the web. Electron doesn't print for me either from the dropdown or Ctrl+P.
