### ISSUE TITLE
Requests to api.ctemplar.com seem considerably slow

### ISSUE THREAD

**Issue by mrusme** [CTemplar/webclient#1134]
### Your environment

Tested over WiFi as well as LTE.

### Steps to reproduce

```sh
curl "https://api.ctemplar.com/emails/messages/?limit=20&offset=0&folder=inbox" \
     -H 'Accept: application/json, text/plain, */*' \
     -H 'Origin: https://mail.ctemplar.com' \
     -H 'Cookie: jwt_auth_cookie=JWT-TOKEN-HERE' \
     -H 'Accept-Encoding: gzip, deflate, br' \
     -H 'Host: api.ctemplar.com' \
     -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15' \
     -H 'Accept-Language: en-us' \
     -H 'Referer: https://mail.ctemplar.com/'
```

### Expected behavior

A decently timed response within around 2 or 3 seconds max (in my case).

### Actual behavior

<img width="497" alt="Screen Shot 2021-04-09 at 4 00 32 PM" src="https://user-images.githubusercontent.com/151967/114240263-dc72b000-994c-11eb-9a6c-ce6f29092c5b.png">

**Comment by The-Hidden-Hand** [comment]
@mrusme 
Thanks for all your reports. We're looking for the bottleneck in the backend, aiming to release a hotfix shortly.

**Comment by The-Hidden-Hand** [comment]
We patched the issue created by a recent update and it works better now. At the same time, we are testing the new ECC keypair support, so all the clients, web and mobile apps, would benefit from faster encryption and decryption actions. Existing users can also upgrade their existing RSA keypair. It should be released in the coming one or two weeks.
