### ISSUE TITLE
Change setting successfully is not reflected on UI

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#1159]
I activated Contact Encryption, the success message was displayed, but the UI input went back to the original Disabled state:

![image](https://user-images.githubusercontent.com/45569116/115676844-8126c180-a33f-11eb-97ab-ab565ff7a301.png)

**Comment by The-Hidden-Hand** [comment]
Related to #1054

**Comment by rock-ejin** [comment]
This issue was fixed in [1054](https://github.com/CTemplar/webclient/issues/1054) branch.
