### ISSUE TITLE
right click support missing?

### ISSUE THREAD

**Issue by ckorder** [CTemplar/webclient#1165]
### Your environment

Linux Mint 20.1 - Ubuntu Focal

CTemplar-2.5.22.AppImage

### Steps to reproduce

I cant right click to copy links, is this intended / normal or is it an obscure bug i noticed ? 

### Expected behavior

I should be able to copy links out of mails. 

### Actual behavior

Right click has no effect at all within mails.

**Comment by The-Hidden-Hand** [comment]
@ckorder 
I've just tried using Firefox for Linux and it worked well.
Are you able to reproduce always? Could you try with a different browser or environment?

**Comment by ckorder** [comment]
I'm using the AppImage
https://github.com/CTemplar/webclient/releases/download/v2.5.22/CTemplar-2.5.22.AppImage

**Comment by The-Hidden-Hand** [comment]
Ok, got it. We are reviewing other issues with the Electron apps and we'll include this one.

Thanks for reporting!

**Comment by ckorder** [comment]
latest release checked still no right click possible please try to make it like:
https://github.com/FreeTubeApp/FreeTube/releases 

its also electron based with working right click. 
it is just me having this issue?

**Comment by The-Hidden-Hand** [comment]
Done @ckorder
Please, let me us know if you have any other suggestion.
