### ISSUE TITLE
Outlook or Ctemplar? - usage of own server infrastructur and signing of releases

### ISSUE THREAD

**Issue by ckorder** [CTemplar/webclient#1191]
### Expected behavior

Please **provide own server side download** instead of pretending to care about user privacy and than **use cloud computing from well known anti costumers privacy advocate** like ms 
### or at least push a hash table of the releases on own servers! 

otherwise this building is totally useless and your doing your costumers a disfavor by opening them to download crap put in the software, when its not even signed. 

of course appimage signing is pointless, because you still need to run the application first being able to detect that
i dont know anyone signing appimages 
https://appimage-builder.readthedocs.io/en/latest/advanced/signing.html#reading-the-signature

i mean you could argue blabla f-droid is the same. yeah it is, but still better than ms and having own servers does not harm you.
because its low to none additional costs, low effort to maintain, get rid of unfriendly companies being affiliated with you! 

if you **have a gitlab.ctemplar.com server** this claim would not exist.

bleak outlook exposed :'(  im disappointed by the low efford 
I mean its still trillion times ahead of other companies but stay straight
this is still no excuse because you sell privacy and no bs, keep that standard and become greater!
making things shine with slogans alone was never a valid proof of skill and skin in the game!

this is to extreme!? yeah sure tell that the webmin users, who had to manage servers with backdoors 
and still cant tell for sure who's to "blame". ( i mean its sure who carries the responsibility always the leaders)

btw: https://ctemplar.com/donate/ any crypto donation is broken
while https://mail.ctemplar.com/donate is working (xmr missing there)

**Comment by The-Hidden-Hand** [comment]
Dear @ckorder ,

We appreciate all the suggestions and contributions you have been making.

About setting our own self-hosted Git repository, that wouldn't be a problem and we had at the very beginning. This changed at some point where we wanted to be using what most open-source developers use, commercially, and we admit to sin.

To be protected against this, all our apps are signed. They are built openly, using Github Actions, then signed. Even the webclient has its checksum + SRI and ways to validate it, I don't know any other website doing this.

Recently some peers from Iran and other countries have been requesting another mirror in a more open place, and we have just launched a mirror at Codeberg: codeberg.org/CTemplar

Links:
- Transparent building **and deploy** logs example: https://github.com/CTemplar/webclient/runs/2631522147?check_suite_focus=true
- Desktop app signatures: https://github.com/CTemplar/webclient/releases/download/v2.5.27/latest-linux.yml, https://github.com/CTemplar/webclient/releases/download/v2.5.27/latest-mac.yml 
- Webclient checksum: https://github.com/CTemplar/webclient/tree/gh-pages#ctemplar-build
- Webclient checksum validation scripts: https://github.com/CTemplar/checksum-scripts

---

> btw: https://ctemplar.com/donate/ any crypto donation is broken
> while https://mail.ctemplar.com/donate is working (xmr missing there)

Solved!

---

Please, let us know if you still have any concern or any other suggestion!
