### ISSUE TITLE
Error: Error decrypting message: Session key decryption failed.

### ISSUE THREAD

**Issue by mrusme** [CTemplar/webclient#1194]
### Your environment

Firefox (latest version)

### Steps to reproduce

- Go to inbox
- Open a message
 
### Behavior

The message should open, which it does. However, in the JS console the following error displays:

```
Error: Error decrypting message: Session key decryption failed.
```

**Comment by The-Hidden-Hand** [comment]
Thanks for reporting. This has been solved in the previous release.
