### ISSUE TITLE
Add a setting to display plain text messages by default

### ISSUE THREAD

**Issue by mrusme** [CTemplar/webclient#1198]
That's probably a very specific use-case/feature, but since I'm using CTemplar in dark mode, reading mail can sometimes become a real PITA.

When people send HTML mails, the text color is sometimes black or even blueish, making it impossible to read on CTemplar's dark mode UI. I did notice that you have implemented "View email in light mode" button for such cases, which helps a lot – thanks for that! 👍🏼 

However, since I personally **really dislike** HTML mails that disrespect the way I want to read my mail, I wish there was a setting that would allow me to turn on some sort of _magic HTML stripping_, so that even if an email does not include a plain-text variant it's still possible to view the mail without having to deal with the bs that HTML mails do.

I don't know if that's something that others would also be interested in. If you believe it's not worth the effort, feel free to simply close this issue. In fact this is really just a workaround for the time being until [something like this](https://github.com/CTemplar/webclient/issues/847#issuecomment-812299777) has become available for CTemplar, so one can use neomutt or aerc with it. :-)

Thank you!

**Comment by The-Hidden-Hand** [comment]
@mrusme 
I agree with you, and in fact, this was half done IIRC, we just need to add an option to enable the text-only mode by default.

For now, you can enable it manually from this dropdown with the `Show plain text` option:
![image](https://user-images.githubusercontent.com/45569116/118538489-c622f580-b73d-11eb-833d-ca5e788c2732.png)

**Comment by The-Hidden-Hand** [comment]
Done @mrusme
