### ISSUE TITLE
Small improvements for the settings page

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#1202]
### Expected behavior

- [x] Create sections to group new settings that have grown. For example, composer font settings.
- [x] Organize some options. For example, `Ask to use local cache` in General has a related setting `Using local/session storage` in Security.

- [x] The following box margin is misaligned:
![image](https://user-images.githubusercontent.com/45569116/118536935-d9cd5c80-b73b-11eb-91e6-97dc2fbedaf0.png)

- [x] Forwarding and Autoresponse page has misaligned margins (compared to the other sections):
![image](https://user-images.githubusercontent.com/45569116/118537162-22851580-b73c-11eb-89e8-29d7d368f6b7.png)

- [x] Given that settings are saved automatically, I don't think the save button is necessary anymore:
![image](https://user-images.githubusercontent.com/45569116/118537254-42b4d480-b73c-11eb-8e0d-734c2219d181.png)

**Comment by The-Hidden-Hand** [comment]
We have to add back the "Ask to use local cache", so the users can reset their setting anytime.

**Comment by rock-ejin** [comment]
Added back `Ask to use local cache` on Settings/Security page.
I made a new group `Local Storage` with  `Ask to use local cache`  and `Using local/session storage` because they are related to each other.
