### ISSUE TITLE
Small improvements for the single mail view

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#1203]
### Expected behavior

- [x] All the HTML emails have what seems to be an `alt` text at the top, which is not intended to appear. It doesn't happen with the text version:
![image](https://user-images.githubusercontent.com/45569116/118538114-501e8e80-b73d-11eb-9e8a-9593ff78b0f5.png)

![image](https://user-images.githubusercontent.com/45569116/118538016-2d8c7580-b73d-11eb-8213-9a87fbb7e697.png)

- [x] These icons are not aligned. The arrow and the star and the date with the label:
![image](https://user-images.githubusercontent.com/45569116/118538241-73e1d480-b73d-11eb-9922-5510a7d99e4d.png)

- [x] After I enter any email, for a few seconds I can see a different value in the emails display name, then it shows the final version:
![image](https://user-images.githubusercontent.com/45569116/118538405-aa1f5400-b73d-11eb-894a-792771dda09f.png)

- [x] The opening animation of this dropdown doesn't match the design (thoughts?):
![image](https://user-images.githubusercontent.com/45569116/118538489-c622f580-b73d-11eb-833d-ca5e788c2732.png)

**Comment by The-Hidden-Hand** [comment]
@rock-ejin 
Another small change, the following setting belongs to the "General" block, just bellow force text plain mode:

![image](https://user-images.githubusercontent.com/45569116/120229293-554f0380-c23c-11eb-9b58-945528a74083.png)

**Comment by The-Hidden-Hand** [comment]
@rock-ejin 
:heart:

**Comment by rock-ejin** [comment]
I think that it is an improvement to align the attachments. 
I will do it next week.
