### ISSUE TITLE
Allow quoting

### ISSUE THREAD

**Issue by PeacefulPotato** [CTemplar/webclient#1204]
### Expected behavior

CTemplar quotes the message being replied to, preferably letting you type your response below the quote instead of above it.

### Actual behavior

When replying to a message, the message being replied to is not quoted.

Also, is mail.disroot.org blocked?

**Comment by The-Hidden-Hand** [comment]
Dear @PeacefulPotato ,

We are about to release a major update including an editor upgrade to the CKEditor later todat. About enabling quoted replies, it was working (a bit buggy tbh) before, so please check if you have it enabled in the settings.

Disroot is not blocked by us. Please let us know more details if you believe there is any connectivity issue and we'll investigate.

![image](https://user-images.githubusercontent.com/45569116/120780539-c1b95380-c517-11eb-9ed2-e86b6fb3f50e.png)

**Comment by PeacefulPotato** [comment]
> Disroot is not blocked by us. Please let us know more details if you believe there is any connectivity issue and we'll investigate.
@The-Hidden-Hand Yeah, I just checked and now all the emails from disroot came in. I don't know what happened but the issue seems to have been fixed.
