### ISSUE TITLE
Attempting to set language to Polish or Romanian returns 'Failed to save changes: [Object object]' error

### ISSUE THREAD

**Issue by vxern** [CTemplar/webclient#1216]
### Your environment

Brave Browser Version 1.24.85 Chromium: 90.0.4430.212 (Official Build) (64-bit)

### Steps to reproduce

Try setting the language to Polish or Romanian.

### Expected behavior

The language should be set to Polish or Romanian and the settings should be saved successfully.

### Actual behavior

The error 'Failed to save changes: [Object object]' is received.

**Comment by The-Hidden-Hand** [comment]
Thanks for the report @vxern 
This is going to be solved in today's release, available in the coming hours.
