### ISSUE TITLE
"Text mode" transformation should better handle newlines

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#1250]
### Description

Check whether we can improve the TEXT mode transformation we do.

### Examples

An email reply, with quoted text, from PROD to DEV, looks it is removing all the new lines:

Original HTML:

![image](https://user-images.githubusercontent.com/45569116/120890835-bab44300-c5f4-11eb-95b5-976dae1c139b.png)

TEXT mode translation:

![image](https://user-images.githubusercontent.com/45569116/120890847-cc95e600-c5f4-11eb-88d5-206a1bf882c5.png)

---

An email from us, sometimes emails are done amazing, but others pooly. This is a poor example:

![image](https://user-images.githubusercontent.com/45569116/120890911-3ca46c00-c5f5-11eb-9b02-b790b00ed593.png)

This is the TEXT-only translation, it basically abuses of the newlines:

![image](https://user-images.githubusercontent.com/45569116/120890929-52199600-c5f5-11eb-9178-40cb99ea5415.png)

**Comment by FP1996** [comment]
related; https://github.com/CTemplar/webclient/issues/1291
