### ISSUE TITLE
Grammar issue

### ISSUE THREAD

**Issue by FP1996** [CTemplar/webclient#1274]
### Your environment

Brave

### Steps to reproduce

Login to webmail. Go to settings, tab "Signatures and Aliases"
Click on "Import Key".
You see a dialog showing with the title: "Import Private Key".
Notice the English explanation text being:

> Please select a mailbox that you want to import key

### Expected behavior

The explanation text should make grammatical sense, in this case appending the word "for" would be enough. I'd add a colon too, personally.

> Please select a mailbox that you want to import key for:

### Actual behavior

Grammar is confusing.

**Comment by The-Hidden-Hand** [comment]
Done. It will be live in the next release.
