### ISSUE TITLE
Pasting email in composer misbehaves

### ISSUE THREAD

**Issue by FP1996** [CTemplar/webclient#1275]
### Your environment

Tried on Brave, tried also on the appimage (2.5.31) on Linux.

### Steps to reproduce

Press 'Compose' and notice how you get a non-fullscreen composer.
Use 'tab' to move to the 'To' field.
Ensure that in your clipboard you have a simple email address. Use a@b.com for instance.
Press Ctrl-V to paste.

### Expected behavior

The client behaves identical to how it would should I have typed this. Specifically I expect that the code which turns an email into a single unit that can be closed is NOT activated due to me not having typed a space or other separator (or left the to field)

### Actual behavior

My pasted email address gets turned into a 'button', not sure how to describe it. It becomes non-editable text with a little close button next to it.
ADDITIONALLY it still has the editable text of the email in the text field. So I now have the email there twice.

**Comment by FP1996** [comment]
Related; pasting an email with the prefix "mailto:" would be nice if it did the right thing and dropped that part.

**Comment by The-Hidden-Hand** [comment]
mailto:thh@ctemplar.com

> Related; pasting an email with the prefix "mailto:" would be nice if it did the right thing and dropped that part.

@superdev0714 
Please review.
