### ISSUE TITLE
attach public key uses wrong mime type.

### ISSUE THREAD

**Issue by FP1996** [CTemplar/webclient#1278]
### Your environment

Linux

### Steps to reproduce

Press compose.
Insert an email address you own to send to.
In the hamburger button (middle bottom of screen) make sure that the following two items are checked;
 - Plain Text
 - Attach public key

(as an aside, notice that the capitalization of those items is inconsistent)

Press send.

### Expected behavior

The email arrives as a multi-part mime type and the attached public key follows the proper mime-type.
For instance 'KMail' uses "application/pgp-keys".

An attachment with the right mime-type also allows users to take action on it, for instance to open it in a pgp app.

### Actual behavior

The email arrived and the public key had mime type "text/plain".

**Comment by The-Hidden-Hand** [comment]
You're right, thanks for reporting.

TODO:

- [ ] Review text capitalization for "Attach public key".
- [ ] Set attached public keys Content-Type as defined in https://datatracker.ietf.org/doc/html/rfc3156#section-7, https://www.rfc-editor.org/rfc/rfc2015.html
- [ ] Ensure upcoming signature function also follows the RFC.

**Comment by The-Hidden-Hand** [comment]
The text change is done and it will be released in the coming days.

We'll be handling the content-type point in the original ticket shortly.
