### ISSUE TITLE
Another PGP/MIME encryption/decryption report

### ISSUE THREAD

**Issue by FP1996** [CTemplar/webclient#1280]
An email sent by KMail gave the error 
> Error: We have got "failed to decrypt this message."

looks like the way that it is encoded there is not supported by CTemplar.
The mail client only shows the content "Version: 1" (see attached message.txt)

The actual test email (minus personally identifiable headers) is attached.

[message.txt](https://github.com/CTemplar/webclient/files/6682926/message.txt)

**Comment by The-Hidden-Hand** [comment]
Thanks for reporting, it arrives in time because we are reviewing the PGP/MIME implementation.

**Comment by superdev0714** [comment]
I think it is heavy related with backend, the app says `Version 1` as email content, it means the backend didn't detect this as PGP/MIME email. We supposed PGP/MIME message has attachment named `encrypted.asc`, but the attachment name that customer shared is `msg.asc`, so I think we can simply solve this issue by adding this case on the backend.
@The-Hidden-Hand  @nitishkansal

**Comment by The-Hidden-Hand** [comment]
You're right. This is related to other opened issues in the backend, let's review there first.

**Comment by nitishkansal** [comment]
Its fixed, as @superdev0714  mentioned attachment name is different and we always expect encrypted.asc in PGP_MIME email. I have added this alternate as well `msg.asc` and tested it and it seems to work fine now.

**Comment by The-Hidden-Hand** [comment]
Please let us know any feedback.
