### ISSUE TITLE
Include official themes as a dropdown with automatic update

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#1283]
### Expected behavior

The themes from https://github.com/ctemplar/webclient-themes are nice but they require manually replace the source code every time there is an update on them. What's the easiest and safest way to include them?

I know giving a drop-down would be nice. Do you think including them in the assets folder and downloading a fresh copy with every production release (extending Github Actions, easy)?

**Comment by superdev0714** [comment]
I think it's good to go work dropdown of themes.

**Comment by The-Hidden-Hand** [comment]
Where to store them? I can help with the themes folder update/sync feature and you do the selection and activation part.

**Comment by superdev0714** [comment]
> Where to store them? I can help with the themes folder update/sync feature and you do the selection and activation part.

I think we can save the css on the database, so whenever one theme is added, managing theme would be done with admin.

**Comment by nitishkansal** [comment]
Added `theme` in user settings which is char field and can store the theme path or name what you want to store per user and it can be updated with setting update.

**Comment by The-Hidden-Hand** [comment]
@nitishkansal 
Are you returning the value anywhere?

**Comment by nitishkansal** [comment]
yes in myself endpoint thats where we send back all user's configurations.

**Comment by The-Hidden-Hand** [comment]
@superdev0714 
Check my last comment, I cannot close the issue because of it.
