### ISSUE TITLE
Removed custom domain, now all mails received on that domain are "gone"(?)

### ISSUE THREAD

**Issue by mrusme** [CTemplar/webclient#1284]
### Your environment

Latest version Firefox & Safari

### Steps to reproduce

1. Add a custom domain / address
2. Receive some mails
3. Disable the address and remove the custom domain
4. All mails received on that domain are gone

### Expected behavior

Mails still visible.

### Actual behavior

Mails nowhere to find anymore.

I assume (and hope!) that this is *only* a display issue and that in fact the mails are still available!

**Comment by The-Hidden-Hand** [comment]
Dear @mrusme,

Unfortunately, the messages and all the data associated with the domains are deleted altogether. I've been checking and found that the confirmation string wasn't clear enough and made the following improvement to explicitly mention messages as I understand are the most important to mention: https://github.com/CTemplar/webclient/commit/fddf019f04e797d362bd05494f0b2df4f6839c7c

I'm sorry for the troubles this may have caused you.

**Comment by mrusme** [comment]
Wow, this is super frustrating. Three weeks ago I lost a handful of mails due to this issue and only after managing to recover these e-mails I found out that now my whole inbox is gone. And it's super weird to have found it out from [third parties](https://cyber-privacy.net/ctemplar-catastrophic-incident-with-complete-data-loss-july-2021/) rather than receiving an official statement in my inbox from CTemplar themselves. :-( 

It has been days after the incident and yet the CTemplar hasn't released any official statement on their website / blog either, making me crawl the info from all sorts of sources in order to find out that something happened, what happened and whether there might still be a chance for my mails to be recovered (at least partially).

**Comment by The-Hidden-Hand** [comment]
@mrusme 
Please provide more information to support@ctemplar.com and I will be handling your case to make sure your account service is restored right now. We are still handling the situation non-stop since Friday.

Thanks for your comprehension.
