### ISSUE TITLE
Move the hard wrap setting to the composer section or add a help text

### ISSUE THREAD

**Issue by FP1996** [CTemplar/webclient#1289]
### Your environment

Firefox on Linux

### Steps to reproduce

Start a new email.

Type or paste text that is wide. More than 80 chars.

Press send.

### Expected behavior

The email as I typed it is send.

### Actual behavior

The email that lands in my 'sent' box and actually arrives at the destination has received line-breaking characters at 80 chars, breaking my formatting and generally causing me to not be certain of what the other other side will see when I press send.

If some sort of line-breaking should be done, it should be done in the editor and the user should have a way to turn it off. The main text of the mail as it is when I'm about to press "send" should be 100% the same as the mail arriving please.

**Comment by The-Hidden-Hand** [comment]
Dear @FP1996 ,

Could you try disabling the `Plain text wrap` setting shown below? It's true that it may need further documentation.

![image](https://user-images.githubusercontent.com/45569116/123135646-91434600-d441-11eb-92b3-d726d96f29ca.png)

**Comment by FP1996** [comment]
That does change the behavior. Thanks!

Now it no longer changes the mail on send.

Enabling does not have any effect on already received emails. (which is what I expect)

My thinking is that this config option should be moved from to "General Settings" to "Composer" group to make clearer what it does, and if you still worry its not clear, maybe append "on send" to the config option.

I for instance only looked at "Composer" options when this happened to me on send.

ps. I would also suggest defaults that are the least surprising, and a post-send wrap certainly surprised me. Probably safe to set it off for new users.

**Comment by The-Hidden-Hand** [comment]
@FP1996 
I was going to make it opt-out for future customers and found it already has `default=False`, so perhaps you enabled it without noticing. We need an option to reset all the settings btw, I'm opening an issue.

@rock-ejin 
I thought this option also affected when reading received emails. In case it doesn't, let's move it to the Composer setting as suggested. Otherwise, let's add a help text indicating what it does.
