### ISSUE TITLE
Notification does not list actual email sender but thread-starter.

### ISSUE THREAD

**Issue by FP1996** [CTemplar/webclient#1290]
### Your environment

Firefox / Linux / KDE

### Steps to reproduce

Be part of an email conversation spanning multiple people, for instance on a mailinglist.
Wait for an email to come in from a person not the initial author.

### Expected behavior

The email that comes in should be used to show who wrote that email in the notification.  
Maybe the subject can be shown for multi-author conversations. IDK.

### Actual behavior

Emails in threaded view are grouped by the first email seen, further emails from other authors do not change the author field (left part in mail-box) and indeed a new email coming from a different author still gives a notification about the thread from the thread-starter instead of the actual author or the subject of the thread.

**Comment by The-Hidden-Hand** [comment]
Thanks for all your reports and suggestions, we'll be sorting and working on them.

**Comment by The-Hidden-Hand** [comment]
This has been solved. Thanks for reporting.
