### ISSUE TITLE
Display test: Leading spaces in text email are not rendered properly

### ISSUE THREAD

**Issue by FP1996** [CTemplar/webclient#1291]
### Your environment

Firefox

### Steps to reproduce

Take an email like this one;
https://mail.kde.org/pipermail/plasma-devel/2021-June/120393.html
and render it in your web client.

### Expected behavior

User typed leading spaces in order to create an indented list.
For instance
```
        * Marco has several branches
```

I expect this to get rendered with those leading spaces.        

### Actual behavior

All lines are displayed fully left-aligned.

Taking a quick look at the inspector I see that the leading spaces nicely land in the generated html. The problem is that normal html whitespace compression means we don't see that.
Likely some replacement of those spaces with `nbsp` tags is needed.

**Comment by The-Hidden-Hand** [comment]
We need to pass the described display test in all our front-ends.
@CTemplar/front-end fyi.

**Comment by The-Hidden-Hand** [comment]
@superdev0714 
Not solved yet. Now if you try composing an HTML email, paste the demo content, it will display fine in the composer but we'll receive it without new lines:

![image](https://user-images.githubusercontent.com/45569116/128704302-96488fcf-5602-4ae3-b0ae-2695e6f1cac9.png)

**Comment by The-Hidden-Hand** [comment]
This was solved.
