### ISSUE TITLE
Thread sorting is reversed (after thread opener)

### ISSUE THREAD

**Issue by FP1996** [CTemplar/webclient#1293]
### Your environment

Firefox

### Steps to reproduce

Get a normal email conversation like on a mailinglist. For instance "Maliit Keyboard and Plasma" from
https://mail.kde.org/pipermail/plasma-devel/2021-June/thread.html

Open this in the mail client and open the thread, but then close all the emails to have a nice overview of order.

### Expected behavior

Email order should be like others do it.
For instance that archive;
![Screenshot_20210625_150657](https://user-images.githubusercontent.com/86202601/123429230-01c79f80-d5c7-11eb-8f90-70bcd9a273ae.png)

And KMail;

![Screenshot_20210625_150739](https://user-images.githubusercontent.com/86202601/123429331-202d9b00-d5c7-11eb-89b3-344bc009f1a3.png)

### Actual behavior

![Screenshot_20210625_150914](https://user-images.githubusercontent.com/86202601/123429493-510dd000-d5c7-11eb-9b12-4954f6713135.png)

If the other apps sort it as 1, 2, 3, 4, 5 then ctemplar sorts it as 1, 5, 4, 3, 2

**Comment by nitishkansal** [comment]
This is fixed @The-Hidden-Hand  It was backend issue: https://github.com/CTemplar/backend/pull/1997

**Comment by The-Hidden-Hand** [comment]
Thanks for reporting.

**Comment by FP1996** [comment]
> Thanks for reporting.

I'm just happy those issues get addressed :-)

Thank you!
