### ISSUE TITLE
settings / folders shows number of "conversations" while it means number of emails.

### ISSUE THREAD

**Issue by FP1996** [CTemplar/webclient#1302]
### Your environment

Firefox

### Steps to reproduce

Have an account with some folders. Put 1 conversation of at minimum 2 emails in it.
Open settings,
go to "folders"
and notice that after your folder there is a text like: "( 2 conversations )"

### Expected behavior

There are actually 2 emails which make up 1 conversation. I expect the message to reflect this. Preferably counting the number of conversations (1) instead of the number of emails.

### Actual behavior

The item lists the number of emails and states that those are conversations, coming up with a much larger number than is the case.

**Comment by The-Hidden-Hand** [comment]
@rock-ejin 
Not fixed yet, this is how empty folders look:

![image](https://user-images.githubusercontent.com/45569116/126733507-cf7c916f-b540-46ed-8135-307b11f2986b.png)

Also, even having content is strange. The format should be: `Demo (20 conversations)`

![image](https://user-images.githubusercontent.com/45569116/126733744-055f3939-027e-4e6c-be44-b6026bdcdd6b.png)

**Comment by OneWhiteBird** [comment]
Seems that this is present again:

![image](https://user-images.githubusercontent.com/80723977/139557237-856701b8-f1da-4d04-99b4-69b1dbf5333b.png)
