### ISSUE TITLE
Deleting a folder loses data.

### ISSUE THREAD

**Issue by FP1996** [CTemplar/webclient#1303]
### Your environment

Firefox

### Steps to reproduce

Have a folder and move an email into it.
Delete the folder.

### Expected behavior

Well, there are two ways this can go.
1. deleting a folder will clearly state that this will delete all emails in that folder. Notice count, amount of bytes and similar. When said folder is removed I expect those emails to end up in the trash, like all emails that I delete do.
2. alternatively deleting a folder will orphan the emails in there and either move them to the trash or move them to the archive.

### Actual behavior

All emails in that folder disappeared without a trace, without a way to get them back.

**Comment by 144** [comment]
in my case deleting a folder moved all the emails from it to "Trash"

**Comment by The-Hidden-Hand** [comment]
@FP1996 
I've just confirmed @144 is right, and the emails go to the Trash folder. Would you please let me know if it was not your case to reopen for further investigation? Thanks for all your comments and suggestions.

**Comment by FP1996** [comment]
I confirmed. Let me give more steps.

1. have a folder with an email in it.
2. confirm that email is also repeated in the 'all emails' folder.
3. go to settings
4. go to folders
5. delete the folder
6. go to trash and notice email not there. Go to all-emails and notice also email is not there.

**Comment by FP1996** [comment]
I don't have the right to reopen an issue you closed, can youreopen it so I can avoid creating a new issue?

**Comment by superdev0714** [comment]
@FP1996  @The-Hidden-Hand 
I couldn't reproduce this one, after deleted the folder, the emails are moved to Trash.
