### ISSUE TITLE
Search emails doesn't find emails if they are not the thread-starter.

### ISSUE THREAD

**Issue by FP1996** [CTemplar/webclient#1304]
### Your environment

Firefox

### Steps to reproduce

Have an email conversation that involves multiple parties (at minimum 3).
Find a user that sent an email that was not the thread-starter and that wasn't you.
Type that user's email address in the search bar and press search.

### Expected behavior

I expect the email from that user, with that email address, to be found.

### Actual behavior

Nothing was found.

**Comment by nitishkansal** [comment]
@The-Hidden-Hand  this is happening because after getting the search results we are fetching parent messages of threads and then preparing the response. Should we just handle individual messages in search whether they are part of any thread or not?

**Comment by The-Hidden-Hand** [comment]
@nitishkansal 
I think that's a good solution and the right behavior. Then we can modify the UI so when you click on any it navigates to the expanded message in the detail view.

Suggestions are welcome.

**Comment by nitishkansal** [comment]
sure let me fix it then.

**Comment by nitishkansal** [comment]
Backend is done for it: https://github.com/CTemplar/backend/pull/2011

**Comment by superdev0714** [comment]
> @The-Hidden-Hand this is happening because after getting the search results we are fetching parent messages of threads and then preparing the response. Should we just handle individual messages in search whether they are part of any thread or not?

I also think this is right logic, btw if the backend processes search like above, why this issue is being raised?
I just think the backend should care only one thing that the user is on whether conversation mode or non conversation mode when processing search.

**Comment by The-Hidden-Hand** [comment]
Solved.
