### ISSUE TITLE
[UX] feedback after search doesn't match search-hint.

### ISSUE THREAD

**Issue by FP1996** [CTemplar/webclient#1305]
### Your environment

Firefox

### Steps to reproduce

In the email section notice that the 'search' hint shows:

> We only support searching email addresses.

go and search for santa and press "Ok".

### Expected behavior

Explain how the **email-address** is not found in any of the emails.

### Actual behavior

The app responds with;

> There are no conversations with this label.

There are two problems with this;

1. I didn't search for conversations. I searched for emails. (see https://github.com/CTemplar/webclient/issues/1304)
2. The usage of "label" is not relevant as we are only able to search for email-addresses.

**Comment by The-Hidden-Hand** [comment]
We have been working on advanced search features (currently testing) and we'll consider and adapt your suggestions for the next iteration.
