### ISSUE TITLE
Unable to refresh / access again a mail opened from the Unread folder

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#1330]
### Steps to reproduce

1. Go to the Unread folder and open a message
2. Copy the URL and try to access it again, even only refresh the current page
3. A blank page will display

### Expected behavior

The URL could change to the real folder in order to prevent such an issue.

- [ ] Additionally, I should be able to edit the pagination number from the URL and it should work. There isn't an alternative for fast-forwarding to older emails, so it has to work I think.
- [ ] Navigation inside messages should bring you to the next/previous unread message, now it fails.

### Actual behavior

The URL stays at Unread path and it is confusing the API filters or something. You have to manually edit to Inbox or the right folder.

**Comment by superdev0714** [comment]
I don't see any solution for this task, when seeing the mail detail in `unread` folder, we are setting this email as `read` up, so refreshing the page would make the request for fetching the mail detail with same id and `unread` folder name and the backend responses empty.

**Comment by nitishkansal** [comment]
It works fine now after fixing it in backend.
