### ISSUE TITLE
Corrupted message when "encrypt to non-CT" is sent to CT

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#1340]
### Steps to reproduce

1. Compose a message
2. Type a CTemplar recipient (or mixed?)
3. Type a message
4. Select "Encrypt for non-CT" and fill the form
5. Go and check the message received at the other CT account

### Expected behavior

Either block the function for CT>CT / mixed, or fix it.

The behavior must be shared by all the frontends.

### Actual behavior

![image](https://user-images.githubusercontent.com/45569116/125608124-e553f593-dbdf-4812-ae30-cb5cde6ec48a.png)

**Comment by nitishkansal** [comment]
It works fine after creating message encryption for CT recipient as well. @superdev0714 @The-Hidden-Hand
