### ISSUE TITLE
Infinite API loop after Bitcoin payment

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#1361]
### Steps to reproduce

1. Sign up from the development server using Bitcoin
2. Wait a minute until the payment is checked (dev only)

### Actual behavior

After the sign-up is complete, I will get a loop of "Cannot check Bitcoin transaction" and a loop calling `/btc-wallet/check/?address=null' until you refresh the window.

**Comment by superdev0714** [comment]
This issue is still on dev? @The-Hidden-Hand

**Comment by The-Hidden-Hand** [comment]
@superdev0714 
Nobody patched afaik.
