### ISSUE TITLE
Button is bigger than others + simple footer fix

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#1364]
### Expected behavior

Settings buttons are consistent.

### Actual behavior

The "Add Folder" button is bigger than any other including other sections.

![image](https://user-images.githubusercontent.com/45569116/126657118-be8ff1cb-9120-41a3-b342-af4d1dfce336.png)

These are also big:

![image](https://user-images.githubusercontent.com/45569116/126657492-2925f4c6-e65a-47d5-ae10-a981636eb4cc.png)

**Comment by The-Hidden-Hand** [comment]
Additionally and CSS related, the footer for the webclient is slightly different. The "Made with love" part is closer to the links than it should, because it is closer to the copyright line in the new design.

![image](https://user-images.githubusercontent.com/45569116/126711953-bf2a825a-e5e8-4815-9730-f8d946c9463f.png)

![image](https://user-images.githubusercontent.com/45569116/126712003-dea36379-d4b3-4564-96f7-2509413f0749.png)

**Comment by superdev0714** [comment]
With 2k (height: 1440px), I don't see any white line, it needs more height? @The-Hidden-Hand

**Comment by The-Hidden-Hand** [comment]
It was because I had an uneven browser zoom setting. It doesn't happen normally.
