### ISSUE TITLE
Fix spacing in custom filter dropdown menus.

### ISSUE THREAD

**Issue by OneWhiteBird** [CTemplar/webclient#1404]
### Your environment

Should be present in all devices

### Steps to reproduce

Open advanced search.
Click on any drop down condition.

### Expected behavior

Fix all spacing in the text.

### Actual behavior

![image](https://user-images.githubusercontent.com/80723977/128379098-03ba67c8-4058-4073-8363-266d8fa5aa85.png)

**Comment by The-Hidden-Hand** [comment]
"Starts With"
"Ends With"

**Comment by The-Hidden-Hand** [comment]
Fixed.
