### ISSUE TITLE
Folder names with odd spacing.

### ISSUE THREAD

**Issue by OneWhiteBird** [CTemplar/webclient#1408]
### Your environment

Non-mobile webclient

### Steps to reproduce

Click on Settings.
Click on Folders menu.

### Expected behavior

Should say Garbage (5 conversations).

### Actual behavior
![image](https://user-images.githubusercontent.com/80723977/128382193-4ebaf9a1-3b2e-4a1d-b371-484f39fd58ef.png)

**Comment by The-Hidden-Hand** [comment]
Duplicated https://github.com/CTemplar/webclient/issues/1302
