### ISSUE TITLE
Forwarded emails don't contain original email address

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#1411]
### Steps to reproduce

1. Receive an email
2. Forward to someone

### Expected behavior

Display the email address.

### Actual behavior

![image](https://user-images.githubusercontent.com/45569116/128445822-25fbe75a-45e2-4c6d-9871-97035a2a787b.png)

**Comment by superdev0714** [comment]
Please specify the issue in details, I don't understand what you're saying.
I think forward mail have not to contain the email in `to` field.

**Comment by The-Hidden-Hand** [comment]
![image](https://user-images.githubusercontent.com/45569116/128685863-989430f6-6c92-4508-8d8e-dafabb5d03bc.png)

The "From" field is missing the original email address.
