### ISSUE TITLE
No way to set primary mail through web interface

### ISSUE THREAD

**Issue by OGALI** [CTemplar/webclient#1420]
### Your environment

Mozilla Firefox 90.0.2 (64-bit) on Linux POP_OS

### Expected behavior
There should be a button to select the default email on the web app.

### Actual behavior
There is currently no way to set the default alias in the web app even when you have a custom domain. However, going in the IOS app, I can select which email I would like to be default, and the change then appears on the web app.

**Comment by The-Hidden-Hand** [comment]
Solved @OGALI
