### ISSUE TITLE
Header encryption for non CTemplar users.

### ISSUE THREAD

**Issue by OneWhiteBird** [CTemplar/webclient#1436]
As per reddit user "flemmepseudo" request:

![image](https://user-images.githubusercontent.com/80723977/132138645-3693ed04-89e6-4bd2-98ec-d71232f61638.png)

Please consider adding header encryption for non CTemplar users.

For future reference:
https://github.com/autocrypt/memoryhole
https://github.com/autocrypt/protected-headers

**Comment by The-Hidden-Hand** [comment]
We can just use PEP protocol: https://github.com/CTemplar/webclient/issues/577

Please let me know if this case would not be compatible or requires any specific change.
