### ISSUE TITLE
Can't view plain text source of an email

### ISSUE THREAD

**Issue by ghost** [CTemplar/webclient#1438]
### Your environment

I'm using Firefox 91.0.2 on Artix Linux.

### Steps to reproduce

1. Receive a patch via git-send-email for an HTML file
2. Try to view it as text (in order to copy-paste the patch into a local file)

![Screenshot_20210908_221705](https://user-images.githubusercontent.com/90352798/132579282-e3d12e76-7100-4d57-a94e-c5712342fe7d.png)

### Expected behavior

The webclient should display the plain text of the message.

### Actual behavior

Nothing changes. The HTML elements are still displayed like on a web page and plain text is unavailable.
As a result, it is impossible to apply the received patch.

**Comment by nitishkansal** [comment]
@The-Hidden-Hand anything needed on this from my side? Because I think if we have the plain text content in the email then webclient can switch to that or the issue is that, we dont have plain text of this email at all?

**Comment by The-Hidden-Hand** [comment]
I think this could be solved with the HTML patch, and the customer is unreachable now.
