### ISSUE TITLE
Import/Move to CTemplar Function IMAP import / Aliases with + sign

### ISSUE THREAD

**Issue by supaeasy** [CTemplar/webclient#1440]
I would like to make CTemplar my main Email-Address. For this I would love an Import Option for my old mails. For example, www.infomaniak.com offers a function like I mean it: Input your IMAP credentials from the old account and all Mails and folders are imported to the new account.

Especially I would wish for an Import Option from protonmail. I guess this would also have to include an Option to import the old Protonmail Private Key to decrypt these Mails.

This would be a huge step towards further adoption of CTemplar as far as I am considered. 

And another thing: one of the few things that really keeps me from changing from PM to CT right now is the Option for unlimited Spam aliases like, when my mailaddress would be "knight@ctemplar.com" i would love to assign a "light" alias to any service such as knight+github@ctemplar.com. Not as a "true" Alias to send from, but just so I may know if my address was leaked to a spamming list *where* it leaked from. PM offers this and I simply love this feature. Any plans on going this way?

Thanks a lot in advance.

**Comment by The-Hidden-Hand** [comment]
Thanks for your comments. We plan to release the feature of importing emails from IMAP during this quarter. There is a current opened ticket on our private board: https://github.com/CTemplar/backend/issues/1660

About the second issue, I made it a task on the backend board so the development can start from there. Mind this quarter is already set and we are not sure to have time for this until the next quarter.

Please let us know any other idea or suggestions you may have.
