### ISSUE TITLE
Email form for people without ctemplar account

### ISSUE THREAD

**Issue by xxxcrow** [CTemplar/webclient#1441]
#### Concept
Hello, when i send somebody outside of ctemplar a protected/deleting email they get that webpage where they can reply
#### My idea
It would be very nice if people without a ctemplar account could initiate it first
Have a form on the website to allow send messages only to ctemplar clients(probably only one recipient , like a private conversation)
And maybe be able to create an account right there(random credentials that will expire), and if they want to upgrade the account they can purchase a plan, or the person who has prime plan can upgrade them(or give the code)
I stumbled upon this idea while i was creating my business-card like website
#### Optional
Also maybe it's possible to generate a link to have anonimous two side conversation:
I talk to somebody, or text not in ctemplar, but i don't want to expose my email for some reasons, i give the person a link where they go and msg me, and i can reply from ctemplar, but they don't see my email
Thank you 😺

**Comment by The-Hidden-Hand** [comment]
Thanks for your suggestions. The idea is good but it would require some serious frontend development and unfortunately the development queue is totally full this quarter. It will still being considered for the next year.

Please let us know if you have any other idea or suggestion for improving the service.

**Comment by The-Hidden-Hand** [comment]
Unfortunately this is not going to become part of the development for the next quarters. However we will keep it in the backlog.

We can reopen later in the future. Thanks.
