### ISSUE TITLE
Allow usage of self-generated pgp keys

### ISSUE THREAD

**Issue by PeacefulPotato** [CTemplar/webclient#1444]
### Expected behavior
While usage of autocrypt is a good idea, especially for non-techies, it would be a good idea if you could upload your own generated key to improve security if you know what you're doing. A warning may be considered to make sure you generate the key securely (4096-bit with a strong passphrase that's at least seven randomly generated words), but I still think it would be a good idea if you allowed advanced users to be able to make and upload their own keys. Thanks!
### Example implementation
See [Countermail](https://support.countermail.com/kb/faq.php?id=84)

**Comment by The-Hidden-Hand** [comment]
@PeacefulPotato 
The function is available for the main address and any aliases: https://mail.ctemplar.com/mail/settings/addresses-and-signatures

![image](https://user-images.githubusercontent.com/45569116/133747012-711bba8f-1b2d-4a5f-a118-2251042204a6.png)

Let us know if you find any difficulty doing so and how we could improve the procedure.

Thanks for getting in touch.
