### ISSUE TITLE
Issue with AnonAddy and Ctemplar (wrong Sender email detected?)

### ISSUE THREAD

**Issue by JustYourAverageGithubUser** [CTemplar/webclient#1457]
I posted this on the Reddit already, but I just found this GitHub and figured it may be more useful if I posted it here.

[AnonAddy](https://anonaddy.com) is "an anonymous email forwarding service that allows you to use unlimited aliases for free." I use it for almost all of my emails for added security, privacy and compartmentalization. There seems to be an issue when using it with CTemplar.

Emails sent from AnonAddy don't seem to thread properly. Here's an image of a test email I did, All of these emails should be in the same thread, but CTemplar has split them. https://files.catbox.moe/f8l5h2.png

Another issue is that when replying to an AnonAddy email (which allows you to reply using said AnonAddy email, which I have my custom domain linked to) CTemplar does not automatically select the proper alias. Presumably because AnonAddy uses the BCC field instead of the "To:" field to handle what address the email was intended for.

I'm sure I'm not the only individual using AnonAddy with CTemplar and would love for this issue to be resolved.

I have already spoken to the guy behind AnonAddy, and he informed me that the issue seemed to be on CTemplar's end. Saying that threading worked for him on his non-CTemplar email connected to Mozilla Thunderbird, but not in the CTemplar email through the web app.

### Your environment

Arch Linux, Firefox 92

### Steps to reproduce

Create AnonAddy account.
Set CTemplar email address as recipient.
Send email from AnonAddy address connected to CTemplar to another email you have access to.
Reply to the email from the receiving address.
Hit reply again through CTemplar

### Expected behavior

CTemplar selects correct alias that AnonAddy address sent to.
CTemplar properly threads replies from AnonAddy addresses into the same email thread.

### Actual behavior
CTemplar does not select proper address for replying, if using multiple aliases and recipient address is not the first alias.
CTemplar does not properly thread emails, instead splitting them into multiple separate threads for each reply. Example: https://files.catbox.moe/f8l5h2.png
(other email providers thread the emails properly with no issues.)

**Comment by The-Hidden-Hand** [comment]
@JustYourAverageGithubUser 
We have been testing and we have found no issue. The reply address the email is gong to be replied is right, and we have checked with other email providers to confirm. The threading is using Message-ID and by checking the first message we can guess it will work just fine. For testing multiple replies it is asking us to have a paid account, so perhaps you can confirm it works or else share an screenshot of the headers for two received messages in a thread with us here or privately at support@ctemplar.com

Thanks for all your comments, they are really appreciated :)

**Comment by JustYourAverageGithubUser** [comment]
Email now properly selects the proper address to reply to, but it does not thread the emails properly.

![testerooo](https://user-images.githubusercontent.com/70122953/142946654-011b2918-b34c-4bb7-9333-383f0424b7c9.png)

I'd be happy to assist further, but would prefer you email me so that we can get right to the issue at hand.
You can email me at: 5oodz8p5@mailer.me (An AnonAddy address to better test the issue.)

**Comment by JustYourAverageGithubUser** [comment]
> @JustYourAverageGithubUser We have been testing and we have found no issue. The reply address the email is gong to be replied is right, and we have checked with other email providers to confirm. The threading is using Message-ID and by checking the first message we can guess it will work just fine. For testing multiple replies it is asking us to have a paid account, so perhaps you can confirm it works or else share an screenshot of the headers for two received messages in a thread with us here or privately at [support@ctemplar.com](mailto:support@ctemplar.com)
> 
> Thanks for all your comments, they are really appreciated :)

I've sent an email to discuss further.
