### ISSUE TITLE
Embeded images do not show up in Gmail

### ISSUE THREAD

**Issue by JustYourAverageGithubUser** [CTemplar/webclient#1458]
### Your environment
Arch Linux, Firefox 92

### Steps to reproduce

1. send email with embedded image to @gmail.com address
2. open email in gmail

### Expected behavior

image should load properly

### Actual behavior

Image does not load.

### Additional info

Other email providers properly load the embedded image, looking it up, this seems to be a common issue to where Gmail will only load images if they are encoded a specific way.

**Comment by The-Hidden-Hand** [comment]
Backend has to replace inline image src data: containing the image encoded as base64 and split into their own content-id. Then use that CID as image src for external email clients to parse inline images.

**Comment by The-Hidden-Hand** [comment]
Solved. Please let us know if there is anything else we could do to improve our service.
