### ISSUE TITLE
Replies add myself as recipient in these two cases and it should not

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#1461]
### Two situations

- Click on the reply button on an email twice with 3 seconds difference
- Click on the reply button on an email where the last message is your reply to someone

### Expected behavior

- [ ] I would never want to reply to myself alone

### Actual behavior

In some cases, I would be replying to myself. This is not right because I would never want to reply myself, even if the last message is my own reply.

**Comment by The-Hidden-Hand** [comment]
@superdev0714 
I was thinking to make it easier. But I don't have any strong arguments.
I've made it optional now.

**Comment by The-Hidden-Hand** [comment]
@superdev0714 
Did you manage to reproduce? They are two different cases, not step 1 and step 2, sorry.

**Comment by JustYourAverageGithubUser** [comment]
`Click on the reply button on an email where the last message is your reply to someone`

This happens to me all the time in back and forth email conversations. 100% of the time if I'm the last person to reply, and I hit the reply button, I'm added to the recipient list.

**Comment by OneWhiteBird** [comment]
I can't seem to reproduce the issue. @JustYourAverageGithubUser could you please test it again?

**Comment by The-Hidden-Hand** [comment]
@OneWhiteBird 
I can reproduce both when the starter of a thread is not me (they are two cases, I didn't make it clear enough).

**Comment by JustYourAverageGithubUser** [comment]
> I can't seem to reproduce the issue. @JustYourAverageGithubUser could you please test it again?

Just replicated it with a long-standing conversation I have with a Gmail user.

**Comment by The-Hidden-Hand** [comment]
@JustYourAverageGithubUser Sorry to bother you again. Could you confirm now?

**Comment by JustYourAverageGithubUser** [comment]
Issue is still present when replying to long lasting thread with gmail user (if I was the last one to reply.)

**Comment by The-Hidden-Hand** [comment]
Got it, we have it tracked already here: https://github.com/CTemplar/webclient/issues/1461
