### ISSUE TITLE
Review these missing translations

### ISSUE THREAD

**Issue by MalteKiefer** [CTemplar/webclient#1482]
Here is a list of strings that are hard coded, please fix to translate these strings:

https://github.com/CTemplar/webclient/blob/2c0b45db0bc7566a83b9a5eb0b52d54194347844/src/app/shared/components/pricing-plans/pricing-plans.component.html#L248

https://github.com/CTemplar/webclient/blob/2c0b45db0bc7566a83b9a5eb0b52d54194347844/src/app/shared/components/pricing-plans/pricing-plans.component.html#L258

https://github.com/CTemplar/webclient/blob/2c0b45db0bc7566a83b9a5eb0b52d54194347844/src/app/mail/mail-settings/mail-settings.component.html#L1270

https://github.com/CTemplar/webclient/blob/2c0b45db0bc7566a83b9a5eb0b52d54194347844/src/app/mail/mail-settings/addresses-signature/addresses-signature.component.html#L488

https://github.com/CTemplar/webclient/blob/2c0b45db0bc7566a83b9a5eb0b52d54194347844/src/app/mail/mail-settings/addresses-signature/addresses-signature.component.html#L491

**Comment by The-Hidden-Hand** [comment]
I'm opening an issue for translating the titles. Let us know any other report
