### ISSUE TITLE
Some emails do not properly display HTML Elements.

### ISSUE THREAD

**Issue by JustYourAverageGithubUser** [CTemplar/webclient#1511]
Some emails look totally fine on desktop, but on mobile are a bunch of gibberish, I think it's probably formatting code that isn't being handled properly on mobile. Every so often, this issue also happens on desktop, but significantly less frequently. 
![vtmbfr](https://user-images.githubusercontent.com/70122953/142161190-c854a2f2-136c-4507-96de-79c7f39c76a4.png)
![x4orpe](https://user-images.githubusercontent.com/70122953/142161196-656adb92-1df7-4922-ac0c-bcae2223fdcd.jpg)

Potentially related bug: Some emails show large amounts of empty space and require scrolling to see the rest of the email, even if the email is meant to fit on most monitors without scrolling. These emails showed up fine on my previous email provider.

### Your environment

Linux, Firefox 94.0

### Steps to reproduce

1. Receive an email formatted in HTML that CTemplar does not support, such as a newsletter.

### Expected behavior

HTML Loads properly.

### Actual behavior

HTML does not load properly and shows lots of garbled code.

**Comment by nitishkansal** [comment]
Anything we need to do here? Because we checked it and didnt find any issues. It could be some issue with bad HTML and maybe the web view we are using on client side needs to be less restrictive? @The-Hidden-Hand

**Comment by The-Hidden-Hand** [comment]
@nitishkansal 
I'm starting to think the problem with recursion limit exceeded is breaking emails (html), because it returns the message partially.

sentry.io/organizations/ctemplar/issues/2249391998/events/ddd46118cbd64dcfb1ed15573e918a65/?project=1290556
sentry.io/organizations/ctemplar/issues/2249391998/events/3aea4c07a0004fd5b0eadf3ec614731c/events/?project=1290556

**Comment by nitishkansal** [comment]
Moving it to progress, let me fix it

**Comment by nitishkansal** [comment]
Recursion error should be minimal now.

**Comment by JustYourAverageGithubUser** [comment]
@nitishkansal 
![mobileCtemplar](https://user-images.githubusercontent.com/70122953/151443575-fb47b788-bfc7-4278-84ed-54ab48f2e10f.png)

**Comment by The-Hidden-Hand** [comment]
@JustYourAverageGithubUser Sorry for disturbing you, but did you still finding HTML issues in the webclient? We are going to review Android in the coming days.

**Comment by JustYourAverageGithubUser** [comment]
@The-Hidden-Hand You're not disturbing me at all, I love participating, please feel free to contact me whenever you need help regarding any issue.

HTML issues seem to be mostly resolved, I have 1 instance where the email Contents were garbled, but unfortunately, it was for a site that's content was personal, so I can't share it with you. But other than that fringe case, HTML formatting has been mostly resolved, from what I can tell.

**Comment by JustYourAverageGithubUser** [comment]
I have just received some emails with more HTML errors.
![image](https://user-images.githubusercontent.com/70122953/152883823-0b99e0a1-979e-4f70-847a-698d9f642dfc.png)
![image](https://user-images.githubusercontent.com/70122953/152883944-f41a3d42-0e06-4c59-9e9e-62a4a6b585f0.png)

**Comment by The-Hidden-Hand** [comment]
Some emails are partially broken. It is like the body part is not being properly detected. Perhaps a broken PGP/MIME.

**Comment by The-Hidden-Hand** [comment]
Merged into parent PGP MIME ticket.
