### ISSUE TITLE
Delete draft confirmation dialogue.

### ISSUE THREAD

**Issue by JustYourAverageGithubUser** [CTemplar/webclient#1512]
When composting an email, the “Delete draft” button just instantly deletes the draft. I would prefer a small confirmation popup tooltip above the button confirming I actually want to delete the draft. I've already accidentally deleted many ready to send emails because the delete button is exactly where the “Send” button used to be on my previous email provider.

**Comment by The-Hidden-Hand** [comment]
Releasing today.
