### ISSUE TITLE
Mobile app does not reply with proper alias.

### ISSUE THREAD

**Issue by JustYourAverageGithubUser** [CTemplar/webclient#1514]
### Your environment

Android 11, CTemplar F-droid App.

### Steps to reproduce

1. Make an email chain with a non-default alias.
2. Reply a few times on desktop using correct alias.
3. Reply again on mobile.

### Expected behavior
Mobile app uses proper alias.

### Actual behavior

Mobile app selects default alias.

**Comment by alexdwork2018** [comment]
https://github.com/CTemplar/android/pull/448
https://github.com/CTemplar/android/commit/eaa1dc5d7f9c8f146bdbad6617b11192fd313a49
Implemented logic for automatically replying to a user's email with the mailbox to which the sender email was received. Optimized code to retrieve addresses for the spinner.
