### ISSUE TITLE
Error: Failed to get public keys

### ISSUE THREAD

**Issue by totallypredictable** [CTemplar/webclient#1564]
### Your environment

- MacOS Monterey 12.1
- Firefox 95.0.2 (64-bit)
- Safari Version 15.2

### Steps to reproduce

1. Go to webclient -> contacts,
2. Edit an existing contact (or create new contact),
3. Click save

### Expected behavior
Contact updated/saved without giving any errors.

### Actual behavior
Getting an error saying "failed to get public keys"

**Note:** This issue only persists when my contacts are encrypted. It never used to happen until today. I was able to exchange pgp encrypted e-mails with my non-cTemplar contacts through automatic public key attachment and e-mail signing. It does not work today. Even though I have my contact's public key saved in their contact book on my mail.

Edit: Also, although I can send pgp-encrypted message to my contact because I had saved his public key in the contact book already, cTemplar does not attach my public-key to the e-mails that I send anymore. Agan, this never used to happen. It worked just fine until today. Public-key attachment option is activated both on my settings (Signature&Aliases -> click edit on my e-mail alias -> enable both "Attach Public Key" and "Sign messages") and on composer.

### Recorded video of the issue:
https://user-images.githubusercontent.com/63866086/147690000-fddaad3e-ec10-47bb-9072-d34e2513b41c.mp4

**Comment by OneWhiteBird** [comment]
Confirmed on my end! Unable to save contact when "Contacts encryption" is enabled.

**Comment by The-Hidden-Hand** [comment]
Webclient is making a post to /keys/ endpoint, not sure why:

```
{"emails":[null]}
```

**Comment by The-Hidden-Hand** [comment]
This is being actively solved as part of another bigger task.
All the functions are being reviewed from the bottom up.
