### ISSUE TITLE
Add drag and drop for easier folder and alias reordering.

### ISSUE THREAD

**Issue by OneWhiteBird** [CTemplar/webclient#1570]
Title.

**Comment by The-Hidden-Hand** [comment]
@PrabhuSuriya It's different from those we had, but I think yours is more built-in or part of the new sdk you use. We could change the others to follow this with the time. Let me know if I should make a ticket.

**Comment by PrabhuSuriya** [comment]
Yes @The-Hidden-Hand we have one more drag-n-drop functionality (in custom filter). We can change that as well to be consistent with the new changes we made. can you create a ticket to track that
