### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by spiritomb108** [CTemplar/webclient#1628]
Hi,
I'd like to contribute to this year's awesome roadmap, so attached ja.json.

I couldn't catch all contexts, so it may contain some unnatural translations. If any problems found after implementation, I will help to fix them.

Thanks.

[ja.json.txt](https://github.com/CTemplar/webclient/files/7966847/ja.json.txt)

**Comment by The-Hidden-Hand** [comment]
@PrabhuSuriya Could we complete the integration? 

@spiritomb108 Thank you! We would like to offer you a year of Prime membership.
Please indicate your username to support@ctemplar.com and show my comment to redeem it.

**Comment by PrabhuSuriya** [comment]
Yes. I'll need to verify the keys with en before adding the language

**Comment by The-Hidden-Hand** [comment]
@PrabhuSuriya Done.

**Comment by Ogheneruona2** [comment]
> @PrabhuSuriya Could we complete the integration?
> 
> @spiritomb108 Thank you! We would like to offer you a year of Prime membership. Please indicate your username to [support@ctemplar.com](mailto:support@ctemplar.com) and show my comment to redeem it.

Done as requested. Thank you
