### ISSUE TITLE
Unable to scroll to the bottom of the webmail using Firefox (last message is half cut)

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#1651]
The last message is half visible, I'm at the bottom most:

![image](https://user-images.githubusercontent.com/45569116/153443893-b5ef996c-39fb-47ef-86d1-82ef255570d8.png)

**Comment by PrabhuSuriya** [comment]
@The-Hidden-Hand I as not able to replicate this in win10/firefox v95.0.2. can you share more info on this? 
os and firefox version, Whether it is inbox and if its happening on pagination. (video if possible would be appreciated)

**Comment by The-Hidden-Hand** [comment]
You are right, I'm unable to reproduce it now! It was Firefox Linux.
