### ISSUE TITLE
Unable to configure custom domain

### ISSUE THREAD

**Issue by fourtwizzy** [CTemplar/webclient#1663]
Duplicate of https://github.com/CTemplar/webclient/issues/1657

The patch does not appear to work. I still am seeing a response that I have gone above my domain limit. I'm feeling tempted to just buy the KNIGHT package to be done with this issue, but it has 4 more domains than I need and is not even a guaranteed workaround. I may somehow be showing as having 10 domains already. If anyone wants to do a screen-sharing session to troubleshoot let me know, I will work with you.

**Comment by The-Hidden-Hand** [comment]
@fourtwizzy Sorry to bother you, but actually I made the mistake of informing you before the production server was restarted and ready to test. Now it's running the latest version and we believe it's working.

If not, could you send an email to support@ctemplar.com with your username so we can check?

Thank you for your patience.

**Comment by fourtwizzy** [comment]
@The-Hidden-Hand Everything is working now. Thanks! ✌⊂(✰‿✰)つ✌
