### ISSUE TITLE
Added hotkeys stopped working

### ISSUE THREAD

**Issue by OneWhiteBird** [CTemplar/webclient#1671]

**Comment by The-Hidden-Hand** [comment]
Reference: https://github.com/CTemplar/webclient/pull/1373

**Comment by PrabhuSuriya** [comment]
@OneWhiteBird Can you give more info on OS/Browser. I checked in Win10/Firefox v95.0.2 (64-bit) and works fine on that

**Comment by OneWhiteBird** [comment]
I'm using Firefox 98.0b7 on Windows 10.

It seems it's related to the about:config setting called privacy.resistFingerprinting, which I had set to True.
