### ISSUE TITLE
appimage for Desktop does not work

### ISSUE THREAD

**Issue by cusco-travel-services** [CTemplar/webclient#1682]
### Your environment

Linux MX-19.4_x64

### Picture, video or steps to reproduce

The file has Execute permissions but nothing happens when trying to run it from a file manager nor within a Terminal window.

In a Terminal window the following happend.

CTemplar-2.5.56.AppImage &
[1] 13854
bash: CTemplar-2.5.56.AppImage: command not found

**Comment by The-Hidden-Hand** [comment]
@cusco-travel-services To execute it please run `./CTemplar-2.5.56.AppImage &`, notice the `./` at the beginning makes the difference. You were calling a bash command instead of executing the file on the current directory.
