### ISSUE TITLE
SimpleLogin validation email doesn't arrive

### ISSUE THREAD

**Issue by OneWhiteBird** [CTemplar/webclient#1684]
### Your environment

Webmail

### Picture, video or steps to reproduce

1. Create an account at https://app.simplelogin.io/auth/register
2. Email does not arrive in the inbox.

**Comment by The-Hidden-Hand** [comment]
postmaster@simplelogin.co contacted us.

**Comment by The-Hidden-Hand** [comment]
> Dear SimpleLogin,
> 
> The header raising syntax error is on your “Reply-To” header.  On the samples received, I didn't find you send a Reply-To header, but I found it mentioned on your DKIM header and I guess that can be the reason. Reference: http://www.exim.org/exim-html-3.20/doc/html/spec_toc.html#TOC807
> 
> For now we have disabled the setting and we'll be waiting for your reply, in case that's the issue and have an easy solution from your side, so we can strictly reject broken headers.
> 
> Regards.

I'll be waiting for their reply.
