### ISSUE TITLE
Compose: HTML editor does not work properly

### ISSUE THREAD

**Issue by OneWhiteBird** [CTemplar/webclient#1685]
### Your environment

Webmail

### Picture, video or steps to reproduce

1. Compose a new message.
2. Try to change text color.
3. When clicking on any of the options, they are hidden inside the box.

### Explanation
![image](https://user-images.githubusercontent.com/80723977/156061657-b2ffc76a-9d39-4def-95ec-ea3e690f93e7.png)

**Comment by PrabhuSuriya** [comment]
Duplicate of Compose formatting options bug (https://github.com/CTemplar/support/issues/480)

**Comment by OneWhiteBird** [comment]
My apologies!
