### ISSUE TITLE
[Electron] Themes not working.

### ISSUE THREAD

**Issue by OneWhiteBird** [CTemplar/webclient#1709]
### Your environment

Latest electron executable (CTemplar-2.5.72.exe)

### Picture, video or steps to reproduce

1. Navigate to settings.
2. Change to any theme.
3. No themes are applied.

Only light mode seems to work.
The button to switch between light and dark mode seems to be working fine.

**Comment by The-Hidden-Hand** [comment]
@OneWhiteBird The patch couldn't be released yet, so you are testing the binary from one week ago. We have to either build it or wait until I can unlock the releases. I'm about to do it now.

**Comment by The-Hidden-Hand** [comment]
Released!
