### ISSUE TITLE
Explicit symetric encryption for non-CTemplar mail users

### ISSUE THREAD

**Issue by OneWhiteBird** [CTemplar/webclient#1722]
### Your environment

N/A

### Explanation

"Encryption for non-CTemplar mail users" is using symmetric encryption, but the code doesn't state which algorithm is used.

It should explicitly use AES 256.

**Comment by The-Hidden-Hand** [comment]
https://github.com/CTemplar/webclient/blob/d47fed077d4cd1fa07f1fd602fcf5d5b08e56e5c/src/assets/static/pgp-worker.js#L645

And related.

**Comment by PrabhuSuriya** [comment]
@The-Hidden-Hand @OneWhiteBird 
Open PGP defaults to AES256 algo. (ref https://www.npmjs.com/package/openpgp/v/4.10.4#:~:text=Encryption%20will%20use%20the%20algorithm%20specified%20in%20config.encryption_cipher%20(defaults%20to%20aes256) )

I have set it explictly to AES 256 in pgp-worker.js
https://github.com/CTemplar/webclient/pull/1723
