### ISSUE TITLE
Get rid of WordPress by enabling SSR (server-side rendering).

### ISSUE THREAD

**Issue by complexparadox** [CTemplar/webclient#234]

**Comment by atifsaddique211f** [comment]
@complexparadox no we don't need to get rid of wordpress, We don't have time to implement all the functionality of wordpress in our site. previously we just had some static blogs posts. Nowe we have lots of blogs posts in wordpress, not just static, our marketing team keeps adding them, to provide this functionality in our system will take a lot of time and we don't even need to do that.

So having wordpress blog is the best for us.
I am closing the issue.
