### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ghost** [CTemplar/webclient#392]
- [x] Add 2FA / U2F
- [x] Add filters (auto-move email to specified folders)
- [x] Content/Subject encryption
- [ ] Add a live chat for support
- [x] Add bulk (entire folder) email selection
- [ ] Add calDAV and calendars
- [x] App for Android
- [x] App for iOS
- [ ] Better folder display and drag to reorder
- [x] Better WYSIWYG editor for emails AND signatures
- [ ] Collapsible sidebar
- [ ] Metadata/Contact encryption
- [x] More cryptocurrency payment options
- [x] Night mode
- [ ] Outlook/Thunderbird compatibility
- [x] Public key for users
- [ ] Sweep function

**Comment by Godfry** [comment]
Thank you for this.  We are putting a pause on new features for now.  But soon we will begin to complete these.

**Comment by notramo** [comment]
> Add a live chat for support

What about using Matrix? It's open-source, encrypted, and federated, just like e-mail. https://matrix.org/
There is also a very good client: https://riot.im/

**Comment by the-hidden-hand** [comment]
I think the idea was to integrate a live chat into the webclient so visitors can reach us directly without having to open another software like email, irc, etc.

**Comment by ZeroAbility** [comment]
Will any of the contact suggestions include support for `.vcf`?

**Comment by The-Hidden-Hand** [comment]
> Will any of the contact suggestions include support for `.vcf`?

Thanks for your suggestion! We've added it to our development pipeline.
