### ISSUE TITLE
Folder scrolling issue

### ISSUE THREAD

**Issue by TheWhiteBird** [CTemplar/webclient#393]
**Actual Results:**
Folder list isn't showing in its entirety because the 'used storage' and 'upgrade account' link are overlaying that portion of the panel. I can't scroll all the way down to access all folders because of this text/link block.

**Steps to Reproduce:**
Create enough folders to overlap the bottom of the screen.

**Expected Results:**
Folder list should support scrolling.

**Comment by TheWhiteBird** [comment]
Also, in Settings, under the Folders tab: when trying to reorder my list of four (4) folders, the arrow buttons aren't working (can't move a folder up or down).

**Comment by Git-R-Goin** [comment]
newbeestar@outlook.com Here's my github email address. I'd like to discuss something with you.

**Comment by atifsaddique211f** [comment]
@Git-R-Goin This issue is already fixed on dev server and soon will be released.
To discuss about the project, I have sent you an email.
