### ISSUE TITLE
Electron client support

### ISSUE THREAD

**Issue by fire-pig** [CTemplar/webclient#405]
Thanks for creating CTemplar!  I'm enjoying using it very much.  I also like the ElectronMail app, which makes it easier to use my Protonmail and Tutanota accounts.  I asked the author of ElectronMail  to support CTemplar, as well.  He declined to do so for now, but it seems he might be interested at some point in the future.  He gave the criteria that would need to be met to add CTemplar support in the future here: 

https://github.com/vladimiry/ElectronMail/issues/139

**Comment by atifsaddique211f** [comment]
@fire-pig Thank you for your support and interest. 
We will keep it in mind and for sure we will support in future.

**Comment by techevanglist** [comment]
@fire-pig We are going to add a very basic version of Electron client of CTemplar

**Comment by techevanglist** [comment]
https://github.com/CTemplar/webclient/releases/tag/v2.3.0
