### ISSUE TITLE
Folder naming issues

### ISSUE THREAD

**Issue by ghost** [CTemplar/webclient#407]
> Folder name must start with an alphabet and can only contain a-z, A-Z, 0-9, ._- characters or space, and minimum length should be 4 characters. 

Allow other languages to be displayed in folders.

@atifsaddique211f 
> I think we just need to change the info text, the idea was to not allow special characters

**Comment by The-Hidden-Hand** [comment]
Thanks for your suggestion! We've added it to our development pipeline.
