### ISSUE TITLE
Allow to press enter after you have typed your OTP passowrd

### ISSUE THREAD

**Issue by Lightningblade** [CTemplar/webclient#488]
After the login with the username and password the OTP dialog appears where you have to type in your 2FA pin. But after you have typed that in it doesn't allow me to press enter to continue. I have to either press tab and enter to get the focus on to the submit button, or press the submit button with the mouse.

**Describe alternatives you've considered**
If you have done this to get the user to pay more attention to their chosen anti Phishing phrase, i'd suggest a more obvious anti Phishing method. People should be able to chose a color, that will then be the background of the OTP page. That might not be as secure, but will be easier to spot right away. 

![image](https://user-images.githubusercontent.com/30607152/72736740-917d4900-3b9e-11ea-88ae-7c09bed3b8ad.png)

**Comment by atifsaddique211f** [comment]
We already have it in our selected for development tasks, it will soon be availble.
Thank you

**Comment by atifsaddique211f** [comment]
fixed.
