### ISSUE TITLE
Website automatically redirects to .onion address while on clear net

### ISSUE THREAD

**Issue by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [CTemplar/webclient#505]
**Describe the bug**
The website worked great for me until like a week or so ago, now whenever I try to access it it redirects me here http://ctemplarpizuduxk3fkwrieizstx33kg5chlvrh37nz73pv5smsvl6ad.onion/ which is very annoying since I want to access it through Firefox, not Tor.

I am pretty sure this has something to do either with FF (although I doubt this) or with my setup, but still it's not something that should happen since this has never happen to me before.

**To Reproduce**
1. Go to 'https://ctemplar.com/'
2. Wait to load
3. See error:

> Hmm. We’re having trouble finding that site.
> 
> We can’t connect to the server at ctemplarpizuduxk3fkwrieizstx33kg5chlvrh37nz73pv5smsvl6ad.onion.
> 
> If that address is correct, here are three other things you can try:
>   *  Try again later.
>   *  Check your network connection.
>   *  If you are connected but behind a firewall, check that Firefox has permission to access the Web.

**Expected behavior**
Be able to connect with CTemplar servers.

**Screenshots**
N/A.

**Desktop:**
 - OS: Debian 10
 - Browser: Firefox
 - Version: 72.0.2
 - Extensions: uMatrix (globally blocking cookies and frames), uBlock Origin (hard mode, globally blocking 3rd party scripts and frames), HTTPS Everywhere (encrypt all sites eligible is on), Cookie AutoDelete (default), Privacy Badger (default) and Decentraleyes (default).

**Smartphone (please complete the following information):**
 - Device: N/A.
 - OS: N/A.
 - Browser: N/A.
 - Version: N/A.

**Additional context**
I'm also using Ghack user.js configuration for my Firefox profile.

**Comment by atifsaddique211f** [comment]
Dear customer
We are very sorry that you are facing this issue.
We do redirect on TOR browser but as it is not completely possible to detect TOR browser, so we try to guess if user is coming from TOR browser bases on some parameters and if they match, then we redirect to onion address for the convenience of TOR user. 
I'm afraid your browser might be meeting those parameters.
Following is the code used for redirection .

```
const torScheme = 'http://';
const torUrl = 'ctemplarpizuduxk3fkwrieizstx33kg5chlvrh37nz73pv5smsvl6ad.onion';
function redirectIfTORBrowser() {
  if (location.hostname !== 'ctemplar.com') {
    return;
  }
  const date = new Date();
  if (window.innerWidth === 1000 &&
    navigator.userAgent.indexOf('Gecko/20100101 Firefox') > -1 &&
    date.getTimezoneOffset() === 0 &&
    (navigator.plugins && navigator.plugins.length === 0)) {
       location.href = torScheme + torUrl + location.pathname;
  }
}
redirectIfTORBrowser();
```
https://stackoverflow.com/questions/28200567/can-i-detect-tor-browser-inside-the-browser-itself-via-javascript-i-suppose

If you just change the default screen size of your browser to not be `1000` then it would resolve your issue.
Otherwise if you can't do that, we will have to disable redirection temporarily and look for solution.
Please let me know how it goes for you after changing the default screen size of browser.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
@atifsaddique211f Thanks a lot for answering so quickly, don't be sorry!

It looks like a really nice feature if you are using Tor as your main browser. The Ghacks' user.js file causes that every time you open a new window the default resolution is changed to that of the Tor browser, I know there aren't a lot of people who have this setup but for those who do it is kind of annoying,since changing it back to the default 1000x800 window would require you to restart the browser,or browse through other website that do apply browser fingerprinting.

I would really love to see this feature implemented but at the same time not having to change my screen resolution, I'll try using https://mail.ctemplar.com/  for now,but please try  to find a better solution.

What about using the time zone of the browser to detect Tor users too? In the URL you provided it says  that Tor browser has a default value of 0 in that regard. Another thing that could be aded is a list of Tor nodes, this won't detect bridges but it's a start.

**Comment by atifsaddique211f** [comment]
@5a384507-18ce-417c-bb55-d4dfcc8883fe For the resolution of this issue, I was thinking of a solution to not force redirect the users, rather if we detect that this is a tor user, we display a notification to the users and ask the if they want to switch to onion address. This would be more user friendly I think and serve the same purpose.
Alert message: 
```It looks like you are using Tor Browser, click here to access our onion address.```

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
@atifsaddique211f I think this is a perfect idea! Should I close the issue now or wait until the changes are applied?

**Comment by atifsaddique211f** [comment]
@5a384507-18ce-417c-bb55-d4dfcc8883fe okay good, then I will apply this solution.
I will close this issue soon when I fix it and PR is merged, until then, we can keep the issue open.

**Comment by atifsaddique211f** [comment]
The solution has been applied. Here is the code.
```
const torScheme = 'http://';
const torUrl = 'ctemplarpizuduxk3fkwrieizstx33kg5chlvrh37nz73pv5smsvl6ad.onion';
const torFieldID = 'redirectToTor';
function redirectIfTORBrowser() {
  if (location.hostname !== 'ctemplar.com') {
    return;
  }
  const date = new Date();
  if (window.innerWidth === 1000 &&
    navigator.userAgent.indexOf('Gecko/20100101 Firefox') > -1 &&
    date.getTimezoneOffset() === 0 &&
    (navigator.plugins && navigator.plugins.length === 0)) {
	  if(localStorage.getItem(torFieldID) === 'true'){
		  location.href = torScheme + torUrl + location.pathname;
		  return;
	  } else if(localStorage.getItem(torFieldID) === 'false'){
		  return;
	  }
	  else if(!localStorage.getItem(torFieldID)){
		  if (window.confirm("It looks like you are using Tor Browser. Do you want to redirect to our onion address?"))
		  { 
			  localStorage.setItem(torFieldID, 'true');
			  location.href = torScheme + torUrl + location.pathname;
		  } else {
			  localStorage.setItem(torFieldID, 'false');
		  }
	  }
  }
}
redirectIfTORBrowser();
```

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
@atifsaddique211f Thanks a lot!!
