### ISSUE TITLE
TOTP 2FA secret key seems fixed for individual accounts

### ISSUE THREAD

**Issue by k3VTSjczL3** [CTemplar/webclient#511]
I have not tested this with multiple accounts, but other users can check on their accounts.

**Describe the bug**
The TOTP 2FA secret key is fixed whether it is disabled or enabled. The secret key should be completely random every time it is set up.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Security'
3. Check the secret key in your authenticator app
4. Click on '2 Factor authentication' (disable it if enabled and re-enable it)
5. Now you should see the secret key matches with the previously stored key
6. Test this several times. Result will be same.

**Expected behavior**
The secret key should be completely random every time it is set up..

**Desktop:**
 - OS: [Linux Mint 19.3]
 - Browser [Firefox, Tor]

**Comment by atifsaddique211f** [comment]
@k3VTSjczL3  We are working on it to have it dynamic instead of fixed value.
Thank you for reporting.

**Comment by atifsaddique211f** [comment]
@k3VTSjczL3 this issue has been fixed.
