### ISSUE TITLE
Broken settings page

### ISSUE THREAD

**Issue by fabianski7** [CTemplar/webclient#524]
Disabling firefox web notifications breaks the CTemplar settings page.

1. Create a new profile (it's best to test in an environment without any other modification than the one that will be made in the next step)
2. Open about:config and change `dom.webnotifications.enabled` to `false`
3. Acess the settings page: https://mail.ctemplar.com/mail/settings/dashboard-and-plans

Screenshots
[Broken page](https://upload.vaa.red/oXVq6#510aed55a43fce99c1741df62c3d7196)
Console: [1](https://upload.vaa.red/2smipW#550fe75db8b7320b2e487c353f018d51), [2 
](https://upload.vaa.red/cK2xc#d128bc8493ef5b4634044aff6f2138c7)

Desktop
 - OS: ArchLinux with Kernel 5.4.24-lts
 - Browser Firefox 74

Additional context
dom.webnotifications.enabled is [not disabled](https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js#L1004) by default in ghacks user.js.

**Comment by fabianski7** [comment]
privacytoolsIO/privacytools.io#1642

**Comment by atifsaddique211f** [comment]
@fabianski7 
I have reproduced the bug, I will fix it as soon as possible.
