### ISSUE TITLE
Reply button

### ISSUE THREAD

**Issue by fabianski7** [CTemplar/webclient#532]
I was answering a long forwarded email and realized I had to go down to the end of the conversation to find the button to write the answer.

Well, I think there should be some more accessible option when replying to an email that was forwarded (normal messages don't have that problem). Maybe in some of those positions that I marked. 

[screenshot](https://upload.vaa.red/XCEPw#334b55245ffe1cfa61612fa9c1c83b2a)

**Comment by atifsaddique211f** [comment]
@fabianski7 there is already an option like that available. look at the screenshot.
<img width="960" alt="Screenshot 2020-03-16 at 10 22 50 AM" src="https://user-images.githubusercontent.com/8865972/76725509-43389080-6770-11ea-973b-7a7ad885de73.png">

**Comment by fabianski7** [comment]
yes it exists, but only at the top of the page. If you scroll the page, [it will not follow](https://upload.vaa.red/2eL9Pe#yFPX5CZCpC4YUBLQ8ndB23XRzsrB29sO), so it is necessary to go back to the top.

**Comment by atifsaddique211f** [comment]
@fabianski7 sure, I will keep in mind.

**Comment by The-Hidden-Hand** [comment]
Thanks for your suggestion! We've added it to our development pipeline.
