### ISSUE TITLE
Link functions to faq

### ISSUE THREAD

**Issue by fabianski7** [CTemplar/webclient#547]
New users may not understand very well what "Dead Man's timer", "Delayed delivery", ... , mean and what they can do. Although this is detailed in the faq, it could exist here too.

Putting a hover box in somewhere ([like this one highlighted in the screenshot](https://upload.vaa.red/25wQfQ#SKSc7EWydodmOH1PlXbSd3T1f9IXydqw)) or just a link in this pop up that is opened in each function, could improve usability.

Another thing: the "Clear" button is not resetting the fields, it's closing the pop up.

**Comment by atifsaddique211f** [comment]
@fabianski7 yes, good suggestion, I will  do it.
