### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by fabianski7** [CTemplar/webclient#553]
You can currently select the timezone from the settings menu, but you cannot select the date format.

The format `ddd, mmmm, yyy` (DMY) is the one [currently used](https://upload.vaa.red/2utMVc#9uGirin4ffIUoSCZ4O8kcgTRyVvdjD4y) on the client and the only one available.

Some more options could be available, such as an abbreviated format and others used in some countries such as YMD and MDY, or allowing the user to create their own.

**Comment by techevanglist** [comment]
@fabianski7 thank you for the suggestion, we will keep in mind.

**Comment by The-Hidden-Hand** [comment]
Thanks for your suggestion! We've added it to our development pipeline.
