### ISSUE TITLE
"Save to draft" and "discard draft" buttons are too close in composer

### ISSUE THREAD

**Issue by notramo** [CTemplar/webclient#564]
It is easy to accidentally click "discard draft" instead of save. Even worse, discarding is done without confirmation dialog: "Are you sure to discard the draft?"

**Comment by techevanglist** [comment]
@notramo I wouldn't agree with accidentally discarding a draft and even if in worst case scenario, you accidentally discard a draft, you get a confirmation that it has been moved to trash, you can easily get it back from trash if you have done a mistake.

**Comment by techevanglist** [comment]
@notramo we are thinking of removing that modal completely, so by default it will save the draft when user click on close icon.

**Comment by notramo** [comment]
It would be good to be able to save the draft without closing the editor (e.g. when composing a long mail, and want to save after every few sentences.

**Comment by atifsaddique211f** [comment]
@notramo the draft is automatically saved when you make changes.

**Comment by techevanglist** [comment]
@notramo The draft is automatically saved when you write something, so you don't need to press any save button again and again.
