### ISSUE TITLE
IPFS-based releases

### ISSUE THREAD

**Issue by notramo** [CTemplar/webclient#578]
Calculating checksums manually is boring, and ineffective. [IPFS](https://ipfs.io) solves this problem by making checksums addresses of the file. This way, if somebody knows the address, the integrity of the file is guaranted.
If two users put the same file into IPFS, the address would be the same.
CTemplar should host the webclient on IPFS too. The IPFS address (SHA256 based checksum) could be displayed on the website, GitHub, Reddit, and other places. It's easy to check on several other platforms (e.g. chat), because one address guarantees the integrity of the entire site.
Users could use the HTTP gateway, by running `ipfs daemon` on localhost, or using IPFS Desktop.
The URL using the local gateway (requires running `ipfs daemon`) looks like this: http://127.0.0.1:8080/ipfs/bafybeidatpz2hli6fgu3zul5woi27ujesdf5o5a7bu622qj6ugharciwjq (makes it easy to ensure the checksum). The above hash is the address of version v2.7.5 of the IPFS web UI, hosted on IPFS. Take a look at their [releases page](https://github.com/ipfs-shipyard/ipfs-webui/releases).
IPFS content can be downloaded too, for those who don't want to run the IPFS daemon, they can easily get a local copy (checksumming is done automatically), and use that version.
It would require some changes (e.g. all **resource** links must be **relative**), there is a tutorial: https://medium.com/pinata/how-to-easily-host-a-website-on-ipfs-9d842b5d6a01
I tried putting the latest release on IPFS, and I had success after inserting the code snippet from the above mentioned tutorial to set the document `<base>` tag, and doing a dirty hack at https://github.com/CTemplar/webclient/blob/435841f04e0b8928577f51765a7b4b60d83bbcbe/src/app/shared/config.ts#L96 to return https://api.ctemplar.com (maybe that function should default to api.ctemplar.com as fallback if no other cases are true)

**Comment by the-hidden-hand** [comment]
Hello @notramo,

Thanks for your suggestions, they are highly appreciated. The technology you share looks interesting but it's new for us, so please give us some time to evaluate its integration because our resources are a bit limited as you may understand.

Kind regards.

**Comment by The-Hidden-Hand** [comment]
Instructions added in PR https://github.com/CTemplar/webclient/pull/580

Official IPFS support was added to our development pipeline. Thanks again!
