### ISSUE TITLE
POP3, IMAP, SMTP support?

### ISSUE THREAD

**Issue by Kreyren** [CTemplar/webclient#605]

**Comment by the-hidden-hand** [comment]
Hello @Kreyren ,

We are on track for supporting external clients with the mentioned protocols because it's one of the most requested feature. While I cannot provide you with an accurate estimation,  I guess it should be publicly released around summer or autumn.

Kind regards.

**Comment by OGALI** [comment]
@The-Hidden-Hand Could you elaborate on how you would be able to support those protocols while still maintaining encryption? Seems to me, the user would be giving up a lot of security features implemented by CTemplar if they elect to choose these protocols on Apple mail for instance.

**Comment by Francewhoa** [comment]
March 14th, 2022 update from CTemplar: _"Currently, CTemplar is not compatible with IMAP/SMTP; however, we are planning to add this functionality in near future. This also means we don’t integrate with email clients such as Outlook, Thunderbird, K9, iOS Mail, etc."_

Source https://ctemplar.com/help/answer/do-you-offer-imap/
