### ISSUE TITLE
rasp pi version

### ISSUE THREAD

**Issue by boistordu** [CTemplar/webclient#827]
could you create a raspberry pi version? or would it be uncompatible with you librairies that you need?

**Comment by The-Hidden-Hand** [comment]
Did you try the Linux desktop app?

**Comment by boistordu** [comment]
yes and it doesn't work, not the good arch @The-Hidden-Hand

**Comment by The-Hidden-Hand** [comment]
I understand now. We have to investigate how to support `arm` on Electron and we will try to implement it.

Thanks for your suggestion.

**Comment by boistordu** [comment]
thanks. I think it actually just needs a recompile with the good option with the node builder

**Comment by The-Hidden-Hand** [comment]
If you want to test, one of these may do the trick:

`npm run build:electron:linux  -- --arm64`
`npm run build:electron:linux  -- --armv7l`
`npm run build:electron:linux  -- deb --dir --armv7l`

**Comment by boistordu** [comment]
Thanks I m going to try

**Comment by The-Hidden-Hand** [comment]
Hello @boistordu , sorry for the wait.

We have updated the readme instructions covering your case please take a look: https://github.com/CTemplar/webclient/tree/dev#build-cross-platform-electron-client

For now, it is only available in the development branch until next week, I wanted to share early access with you.

Thanks for getting in touch, let us know if you have any further suggestion.
