### ISSUE TITLE
Move to Codeberg or another free place!

### ISSUE THREAD

**Issue by musicsd** [CTemplar/webclient#847]
Unfortunately, CTemplar does not yet have the features of a free application. The source code is CTemplar on GitHub, it does not have the IMAP and SMTP connection feature.

The first is a priority; CTemplar says our program is "free and open source", but it is not!
If the application is located in a free and open source location such as Codeberg, the application will be free and open source.
GitHub boycotts Iranian users, mocks RTL, removes apps, is not open source, and more ...
Please add IMAP and SMTP feature as well, thanks.

**Comment by The-Hidden-Hand** [comment]
Thanks for your comments. Implementing IMAP and SMTP support is planned but we don't have a release date yet because we have to overcome some complicated scenarios added by the encryption layer we apply when compared to common email providers. About the concerns with GitHub I don't know what to answer, but I have forwarded your message to our CEO.

**Comment by Godfry** [comment]
@musicsd We can't just flip a switch and offer IMAP & SMTP.  We're working on it now and we expect to release IMAP & SMTP support in early 2021.  I also think you have valid concerns about Github, we're going to study this and likely make changes.  
Paul M
CTemplar Founder/CEO

**Comment by Godfry** [comment]
@musicsd We've reviewed this in detail and we've agreed with your suggestion to use Codeberg.  We're going to use it as well as Github.  We've added this task to our development schedule.  When we finish with this task we'll publish a blog post to explain why and we'll mention some of the reasons you outlined. 
Kind Regards,

**Comment by The-Hidden-Hand** [comment]
- [ ] Push a remote copy of the repositories to codeberg
- [ ] Backup issues with github.com/zauberlabs/github-issues-backup
- [ ] Reference this repository as an alternative on other places where we mention Github
- [ ] Create a blog post

**Comment by The-Hidden-Hand** [comment]
- [ ] Push a remote copy of the repositories to codeberg
- [ ] Backup issues with github.com/zauberlabs/github-issues-backup
- [ ] Reference this repository as an alternative on other places where we mention Github
- [ ] Create a blog post

**Comment by mrusme** [comment]
Hey there @Godfry, any news in regard of the IMAP & SMTP integration? Would something similar to [hydroxide](https://github.com/emersion/hydroxide) work for CTemplar as well, if you were to implement a Proton-like API?

**Comment by The-Hidden-Hand** [comment]
This is coming on: https://codeberg.org/CTemplar
I just have to plug in the Github Action to migrate the code.

**Comment by The-Hidden-Hand** [comment]
It's done! @musicsd 
https://codeberg.org/CTemplar

Please let us know if you have any other suggestions.
