### ISSUE TITLE
Unable to create account

### ISSUE THREAD

**Issue by SecretestSquirrel** [CTemplar/webclient#855]
Running Ubuntu 18.04, on Tor Browser 10.0.4, http://mail.ctemplarpizuduxk3fkwrieizstx33kg5chlvrh37nz73pv5smsvl6ad.onion. Filled out username and password, selected Prime paid account, selected to pay in bitcoin. Was given a qr code and address along with one hour time to pay .0451 BTC, or ~$72. Did so, and was confirmed within the first 10 minutes.

Tried to create the account as soon as I sent the bitcoin, after confirmation, then for the entire hour the timer counted down. It failed at various points in the process the whole way. Sometimes making it to the end, saying account created and saved in Iceland servers, then saying it failed as it presented a blank "recovery code". Tried logging in with the credentials I had entered but was denied entry.

Not sure what the problem is/was, I've emailed support to see what can be done. Figured I'd throw something here as well. Really wanting to get off ProtonMail, so I let my bitcoin paid account lapse there so I could instead move here to an open source version. Hope this can be resolved.

**Comment by SecretestSquirrel** [comment]
Follow up to this, support responded quickly to my email and got me sorted with a proper Prime account. I created it on Tor Browser for Android with no issue. Appreciate the response, hopefully this was just a one-off issue with a device or network.

**Comment by The-Hidden-Hand** [comment]
Thanks for the follow up. Please let us know if you find anything we can improve at anytime.
