### ISSUE TITLE
Email body blank in dark mode

### ISSUE THREAD

**Issue by SecretestSquirrel** [CTemplar/webclient#858]
**Describe the bug**
After selecting dark mode in Tor Browser webclient, the body of emails does not show up. Only a blank, white screen with either no text or partial text off to the side is shown. Switch back to dark mode disabled and the text shows.

**Steps to reproduce the behavior**

1. Go to 'Dark Mode'
2. Click on 'Enabled'
3. Open email inbox, open any message

**Your expectation**
Email body should show.

**Environment**

- OS: [Ubuntu and Android GrapheneOS]
- Device: [Lenovo laptop and Pixel 3a]
- Browser: [Tor Browser 10.0.4]

**Screenshots**
Attached
![Screenshot_20201116-234539_Tor Browser](https://user-images.githubusercontent.com/74485231/99591295-94aeb480-29bc-11eb-9a2d-8f4de411392e.jpg)

**Comment by The-Hidden-Hand** [comment]
Thanks for reporting. The dark mode is work in progress and we plan to release an improvement to make it usable in the next few days. Please let us know if you find anything else we should improve and we'll make our best.
