### ISSUE TITLE
E2EE email badge icon differentiation

### ISSUE THREAD

**Issue by SecretestSquirrel** [CTemplar/webclient#891]
**Feature request**
One suggestion for the AppImage webclient. When viewing inbox for example, there are icons on the right of the page that show security measures employed for each email. My suggestion is to make a clear differentiation between emails that are end-to-end encrypted by CTemplar and those that are not. As of now, the only way I can see to actually tell the difference is to move the cursor over the E2EE badge icon. Emails that are not encrypted by CTemplar do nothing, where emails that are encrypted by CTemplar show a popup message saying as much. It may seem a small thing, but in my humble opinion it is these sort of small things that sometimes lead to problems for "normal" users, for lack of a better term.

**Possible solution(s)**
Seems reasonable to either:
- Remove the E2EE badge icon from emails not encrypted by CTemplar client
- Change the color or display in some way where encrypted emails are easily denoted differently

**Context**
Admittedly this is may be a minor thing for some, but I'm of the opinion the more clear the difference between CTemplar E2EE emails and those that aren't is made, the better. Users should be encouraged to spread CTemplar E2EE email clients obviously, not to mention a change such as this eliminates more errors that users may make accidentally by thinking they are writing an encrypted email when they actually aren't. Also, something as small as having an icon present or differently displayed gives users a sort of goal to achieve by wanting all their emails to appear with this "special" encrypted icon. As it stands, all emails appear at first glance to be the same, since they all present the icon in a way that is indistinguishable without doing further action with the cursor. 

As an example, one of these three emails is E2EE by CTemplar, the other two aren't. Which is which? 
![E2EEIcon](https://user-images.githubusercontent.com/74485231/102698157-34b56300-4233-11eb-9bc3-a0cae9a5f6f2.png)

**Comment by Lissy93** [comment]
+1 
It's caused by a missing CSS class, called `.text-faded` which isn't defined when in dark mode (see [`generic-folder.component.html`](https://github.com/CTemplar/webclient/blob/master/src/app/mail/mail-list/mail-folder/generic-folder/generic-folder.component.html#L297)). It's only a very minor UI issue, but I agree with you that it should be fixed, since it may give the user a false sense of security

There are many issues similar to this, caused by the current implementation of the dark theme, I think this feature really needs to redone and coded properly

**Comment by happyman125** [comment]
@The-Hidden-Hand what is each meaning of below two images? I think they are displayed together. Why we need to display two images?
![image](https://user-images.githubusercontent.com/43462128/104359466-5ba44380-5518-11eb-9537-62754583042e.png)

**Comment by The-Hidden-Hand** [comment]
For reference:

- The shield indicates the messages are encrypted at rest with zero access encryption. This applies to all messages sent and received using CTemplar.
- The tower indicates the message is protected by CTemplar's 4-wall technology where it is fully protected by e2ee. This happens to all messages sent between CTemplar users.
