### ISSUE TITLE
Glitch after logging out while the mailbox is loading

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#898]
### Your environment

Firefox.

### Steps to reproduce

1. Go to mail.ctemplar.com and log in.
2. Logout before it finishes loading the mailbox.

### Expected behaviour

All actions are cancelled and there is a clean logout without glitches.

### Actual behaviour

Some elements will show as if you were logged in.

**Comment by SecretestSquirrel** [comment]
I have also experienced a similar issue on the Android mobile app on occasion, fyi. Generally occurs when in another tab, say "Sent" emails, then press back button which takes you to "Inbox", which shows as loading. If I hit the back button again while loading in an attempt to exit, I sometimes get an app crash.

Can open an issue in Android repo if you'd like.
