### ISSUE TITLE
Unable to close composer window while attachments are being uploaded

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#899]
https://prnt.sc/vvlqf7

It should ask if we want to stop uploading the files and save the draft, otherwise propose a better UX.

**Comment by happyman125** [comment]
@The-Hidden-Hand  I need to confirm with you. I think we don't need to ask with any modal or popup.
This action includes two actions: cancel uploading + close compose. These two actions doesn't ask to confirm so our action also doesn't need to ask.
I am going to implement without asking so 
when close Compose while uploading attachments, first cancel uploading and close compose window.

**Comment by The-Hidden-Hand** [comment]
@happyman125 Best practices on UX suggest we confirm destructive operations. In this case, the upload and encryption progress will be lost if canceled before sent to the API.

**Comment by The-Hidden-Hand** [comment]
@happyman125 Otherwise I won't allow closing the window, but now looks like the closing button isn't working. This was reported by Mahesh, confirm with him, Paul, or chat if you want different opinions.

**Comment by happyman125** [comment]
@The-Hidden-Hand I always respect your opinion. but although we display modal to confirm operation, we can't PAUSE process at that time. So at that time, the process is being still. it means confirm modal is not needed.

I also checked gmail and it has no confirm modal due to same reason.

**Comment by The-Hidden-Hand** [comment]
I'm not asking to pause the upload :thinking:

**Comment by Godfry** [comment]
Can we continue the upload, and also give a popup saying they will lose data?

**Comment by The-Hidden-Hand** [comment]
@happyman125 I found this may be creating a glitch on drafts and the composer.

How to reproduce:

1. Remove all the drafts.
2. Compose a new message.
3. Fill in a subject.
4. Upload 3 files enough big so you have time.
5. Close window, answer no.
6. Close window, answer yes.
7. Go to the drafts folder and you can notice the draft is corrupted.
8. If you open the draft or a new composer window, you won't be able to close it anymore, looks like the webclient crashed.
