### ISSUE TITLE
Cookie “jwt_auth_cookie” deprecation notice

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#912]
### Your environment

Firefox, at least, and others could follow.

### Steps to reproduce

1. Open JS console.
2. Go to mail.ctemplar.com and login.
3. Logout and check console output.

### Actual behaviour

> Cookie “jwt_auth_cookie” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

### Notes

I'm not sure if the warning comes when unsetting the cookie or it is because of a real misconfiguration.

**Comment by superdev0714** [comment]
@The-Hidden-Hand 
I am sure we can ignore this message.
Below is delete_cookie source on Django.
`def delete_cookie(self, key, path='/', domain=None, samesite=None):`
    `self.set_cookie(key, max_age=0, path=path, domain=domain, samesite=samesite, expires='Thu, 01-Jan-1970 00:00:00 GMT')`

When signing out, our backend tries to delete cookie. From the above code snippet, `delete_cookie` does actually set new cookie with empty value and expires date = 1970. This is why broswer doesn't have remove cookie concept. Of course this new cookie doesn't handle Secure attribute. So the broswer says about expires of cookie and SameSite & Secure attributes.

**Comment by The-Hidden-Hand** [comment]
@superdev0714 Do you think it has to do with [this setting](https://github.com/CTemplar/backend/blob/master/app/settings.py#L71)?

**Comment by superdev0714** [comment]
I don't think that setting is related with above problem.
We should set `SameSite = None` and the setting is correct.
Although `SameSite=None`, If `Secure` flag is set, the above console would not be raised.
https://github.com/CTemplar/backend/blob/53048d5de26fab1489cdbfc47a8025ebe1b9eab3/app/users/views.py#L59-L68

The warning console is related with how Django deletes the cookie as I explained above.

I think we can completely ignore this problem.
