### ISSUE TITLE
10 Small UI Bugs

### ISSUE THREAD

**Issue by Lissy93** [CTemplar/webclient#916]
Hello & Happy New Year!

Nothing to serious here, just a couple of small UI-related issues I've while using the web app recently. Thank you very much for fixing all the Android bugs I raised a couple months back- really appreciate it :)

For reference, I'm using either Firefox in Arch, or Brave Browser on Windows Pro 64-bit. All the issues show up on both those platforms. 

Please do let me know if you need any more info on anything below.
Thanks very much,
Alicia

---

### Authentication Error while using the Tor version

While using Tor, account login works fine, but no emails or account-related content is loaded. This is caused by `user_key` being deleted from the Local Storage immediately after being set. (Although I am unsure the reason why it is being deleted). It results in all GET requests responding with a 401 (For example the `unread/` endpoint error with: `Authentication credentials were not provided`).

---

### Failed to Upload Attachment

While using the free plan, small attachments can be uploaded just fine. Attachments over 10 mb show a Toast message and are not uploaded, as expected. But for attachments that are above 8 mb, and below 10 mb, no toast message is shown, and instead the server responds an error and the POST request to `https://api.ctemplar.com/emails/attachments/create/` returns a `400`.

This might be caused by a discrepancy between the value size limit specified on the backend, or how it is calculated. But I cannot test this as I don't have access. The size from `event.dataTransfer.files[i].size` in [`compose-mail.component.ts`](https://github.com/CTemplar/webclient/blob/master/src/app/mail/mail-sidebar/compose-mail/compose-mail.component.ts) works correctly

Also, when I try to upload many attachments at once, I sometimes get the following CORS error:
`Access to XMLHttpRequest at 'https://api.ctemplar.com/emails/attachments/create/' from origin 'https://mail.ctemplar.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

---

### Mail Previous & Next Buttons become Disabled Incorrectly

After applying an action to an open email, and being sent back to the inbox, the `disabled` attribute is applied to the email navigation buttons, despite having additional pages of emails, preventing the user from getting the next page.

![Short screen recording of the issue](https://i.ibb.co/z25v98x/ctemplar-disabled-buttons-issue.gif)

Steps to recreate: Login normally and wait for the inbox to load, click an email and wait for it to load, apply an action (e.g. 'Archive' or 'Move to folder') to the currently open email and wait, now once back to the inbox hover over the next/ previous buttons and observe navigation buttons in disabled state. 

This happens because `ngOnInit()` runs only once, (after all data-bound properties of a directive have been initialized), whereas class attr variables get re-defined whenever the user is navigated back to a component that is already initialized. So `MAX_EMAIL_PAGE_LIMIT = 1;` replaces the current value of `mailState.total_mail_count` in [`generic-folder.component.ts`](https://github.com/CTemplar/webclient/blob/master/src/app/mail/mail-list/mail-folder/generic-folder/generic-folder.component.ts). The [HTML file](https://github.com/CTemplar/webclient/blob/master/src/app/mail/mail-list/mail-folder/generic-folder/generic-folder.component.html#L163) is using this variable to set the disabled state of the `.mail-nav-control-next` button.

---

### Unable to Edit Subject Field

When replying to an email, the subject field becomes uneditable, as it has the `disabled` attribute assigned.

This seems to have been done purposely, in [`compose-mail.component.html`](https://github.com/CTemplar/webclient/blob/master/src/app/mail/mail-sidebar/compose-mail/compose-mail.component.html#L163) with `[disabled]="action === mailAction.REPLY || action === mailAction.REPLY_ALL"`.

Is there any technical reasoning behind this? As there are many reasons why the user would need to modify the subject before sending, and currently you need to go into dev tools, and manually remove the `disabled` attribute to do so, which isn't so user friendly

Also, while I'm here, on the same line of code, for `ngModelChange`- you shouldn't need both of these subject update calls `valueChanged$.next(mailData.subject); onSubjectChange(mailData.subject)`- (especially since there isn't currently a way to change the subject!) But also because sharing data wherever possible is always a better approach in terms of stability and consistency

---

### Ever-Loading Spinner for Emails Addresses that are not CTemplar

When replying to an email, where original senders email is not a CTemplar address, the loading spinner in the recipient chip spins indefinitely. (This does not happen when replying to an @ctemplar address)

This happens because `getUserKeyFetchingStatus()` (in [`compose-mail.component.ts`](https://github.com/CTemplar/webclient/blob/master/src/app/mail/mail-sidebar/compose-mail/compose-mail.component.ts#L1757)) returns true, because it's assigned in the [`compose-mail.reducers.ts`](https://github.com/CTemplar/webclient/blob/master/src/app/store/reducers/compose-mail.reducers.ts#L77)

![Screenshot](https://i.ibb.co/nrDKQwq/ctemplar-spinner-always-loading.gif)

(Also, the spinner does not show when dark theme is enabled, as the colors are too similar)

---

### Unable to Apply Actions if button pressed before Decryption is Complete

In the inbox view, if you use the Select All checkmark, without realizing that some emails near the bottom have not yet finished loading, then wait for everything to finish loading, the action buttons remain in a disabled state.

Caused by `noEmailSelected` being set to `true` in [`generic-folder.component.ts`](https://github.com/CTemplar/webclient/blob/64325287ba0e75b533d49a2605cb95dddfe4ad93/src/app/mail/mail-list/mail-folder/generic-folder/generic-folder.component.ts), and not updating once loading is complete

---

### Pop-out Reply Broken

When replying to an email, the button for switching between pop-up and inline editor is not working.

Steps to recreate: Log in to CTemplar, open up any email, click "reply", then click "Pop out reply", nothing happens and the following error is thrown: `TypeError: onChangePopup is not a function`

In [`compose-mail.component.html`](https://github.com/CTemplar/webclient/blob/64325287ba0e75b533d49a2605cb95dddfe4ad93/src/app/mail/mail-sidebar/compose-mail/compose-mail.component.html#L505) a call is make to `openReplyinPopup()` in [`compose-mail.component.ts`](https://github.com/CTemplar/webclient/blob/64325287ba0e75b533d49a2605cb95dddfe4ad93/src/app/mail/mail-sidebar/compose-mail/compose-mail.component.ts#L687) which attempts to call `this.popUpChange.emit({...})`, which has the value of `onChangePopup($event)` in [`mail-detail.component.html`](https://github.com/CTemplar/webclient/blob/64325287ba0e75b533d49a2605cb95dddfe4ad93/src/app/mail/mail-detail/mail-detail.component.html#L397), and this function does not exist.

---

### Security Status Icon Incorrectly Displayed

In the inbox view, emails sent within CTemplar correctly display the E2E icon, however for emails which are NOT sent through any encrypted means still display the E2E icon is still shown when in dark mode

This is caused by a missing CSS class, called `.text-faded` which isn't defined when in dark mode. It's only a very minor UI issue, but since it may give the user a false sense of security, it should be addressed

![Screenshot](https://i.ibb.co/y4b1Q0C/ctemplar-security-icon.png)

---

### A new Reply element displays for each edit

After opening an email, clicking reply, discarding draft, then next time I open the email I have multiple Reply or Forward email forms. For an example of what I mean, see [this screenshot](https://i.ibb.co/f0SZDgX/email-chain-error.png). This becomes very hard to manage when dealing with long chains of emails, which end up having 6 different Reply forms, I believe it's caused by a duplication in the store

---

### Soft Keyboard Prints User's Password

When entering login credentials using the virtual keyboard, each character typed is also outputted to the console in plaintext (called from [`users-sign-in.component.ts`](https://github.com/CTemplar/webclient/blob/master/src/app/users/users-sign-in/users-sign-in.component.ts#L278)). This may make some users feel uncomfortable, as it's not uncommon for websites to pipe console output to an error reporting service (I know CTemplar does not do this though)

![screen-recording](https://i.ibb.co/Bn79RSV/Ctemplar-password-issue.gif)

Console output should be disabled on your production build. But also it's generally very bad practice to merge any code that still has debug statements left in. There's a few more occurrences of console.log within the CTemplar app, including one which prints the users entire email reply, in [`compose-mail.component.ts`](https://github.com/CTemplar/webclient/blob/64325287ba0e75b533d49a2605cb95dddfe4ad93/src/app/mail/mail-sidebar/compose-mail/compose-mail.component.ts#L633). Ideally all of these should be removed

---

### Mouse Pointer Reverts Back to Default

In the inbox view, when hovering over an email, there is a spot where the cursor reverts back to `default`.
This can be fixed in `generic-folder.component.scss`, under `.display-emails label` add: `cursor: pointer;`.
![Mouse pointer style](https://i.ibb.co/1frcTdt/ctemplar-pointer-ui.gif)

---

### Dark mode makes all almost all HTML-based email content illegible

When in dark mode is enabled, most HTML-based emails become very hard to read. This is because is forces the email to have a dark background, while a common theme for many HTML-based emails at the moment is very dark grey text on an unset (intended to be white) background.

![Example of how emails appear in dark mode](https://i.ibb.co/JzmLRjC/ctemplar-dark-001.png)

Each email appears slightly different, so here are some more examples to better explain it: [1](https://i.ibb.co/p1tWK85/ctemplar-dark-003.png), [2](https://i.ibb.co/89Tg33y/ctemplar-dark-005.png), [3](https://i.ibb.co/rb28R3V/ctemplar-dark-002.png)

A quick solution to the issue of illegible HTML-based emails, would be to keep the email body white, unless the email was written in plain text or rich text. E.g. `app-mail-detail .mail-content * {	background: #fff; }`.
I've seen this done on ProtonMail and a couple of other email providers, and it makes sense, since it's going to be a complex task to attempt to modify colors when every HTML email is different, and most users don't like the formatting of an email body being modified by their client unnecessarily.

Alternatively, this element can be targeted using the `show_gmail_extra` class (out of interest, why do many of the class names start with .gmail?).

Actually, there are a lot of other issues with the dark theme, mostly in the form of UI inconsistencies, but caused by the code within [/src/assets/css/dark-mode.css](https://github.com/CTemplar/webclient/blob/master/src/assets/css/dark-mode.css). This current method just lists a bunch of classes, and uses pseudo ::before and ::after selectors to overwrite the color attribute to a hard-coded hex value followed by the `!important` directive. There are several problems with this solution, but in this case it has lead to many elements get left off causing inconsistencies and visual bugs. The use of overides shouldn't be misused like this.

When it comes to colors, a neater approach would be to utilize variables (either native CSS or within SASS)- that'll make consistently applying the same colors the different elements a lot clearer and easier. Once all colors defined as constants then you can just conditionally import either the dark or light pallet depending on user preference with a simple Angular service.

More examples of broken dark theme content
- `.mt-2` text remains black
- `.modal-content-email` has a white background and white text
- `.attach-uploader` has a white background and white text

---

### Buttons, Images and Form Elements are not Accessible

Overall this is not too bad, just a couple of small things to fix. For some people (e.g. whose who rely on screen readers, or have other special requirements) a websites that doesn't meet these standards may be totally unavailable to them, so personally I believe this is important in order to avoid unfairly excluding anyone
- Buttons do not have an accessible name
- Image elements do not have [alt] attributes
- Form elements do not have associated labels
- Links do not have a discernible name
- [user-scalable="no"] is used in the <meta name="viewport"> element or the [maximum-scale] attribute is less than 5

I recommend implementing [Pa11y](https://pa11y.org/) into your CI process, it's a wonderful tool and it makes monitoring accessibility standards really easy

**Comment by happyman125** [comment]
I need to confirm these two items of github 916.
1. A new Reply element displays for each edit
2. Unable to Apply Actions if button pressed before Decryption is Complete
I can't reproduce on my side so I hope you check on your side or we will need to request more details from lissy
