### ISSUE TITLE
Search UI in small screens is unfinished

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#918]
### Your environment

Firefox mobile.

### Steps to reproduce

1. Go to CTemplar inbox having small screen (mobile-like)
2. Check and test the search bar

### Expected behaviour

The input field and icons are looking great, aligned, and with a consistent design style.

I'm able to search.

### Actual behaviour

The search input is glitched, icons are misaligned and seem like they belong to different icon sets because their style doesn't match.

I'm unable to search.

![image](https://user-images.githubusercontent.com/45569116/104168828-8e561b00-53f6-11eb-8362-888544eb28f8.png)

![image](https://user-images.githubusercontent.com/45569116/104168763-75e60080-53f6-11eb-9af4-f426f03f383e.png)

![image](https://user-images.githubusercontent.com/45569116/104179981-8b622700-5404-11eb-8ee8-c06285e2ed7f.png)

**Comment by The-Hidden-Hand** [comment]
@happyman125 
I feel it can be improved a bit more. The icons look uneven, and overall it looks like an unfinished feature.

**Comment by happyman125** [comment]
@The-Hidden-Hand As for uneven icons, maybe it is from several icons set now. If we use one style design assets, this can be fixed. how do you think?

**Comment by The-Hidden-Hand** [comment]
@happyman125 
Whatever you prefer to solve the issue.
