### ISSUE TITLE
Desktop notifications support in Electron apps

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#951]
### Expected behavior

The notifications sent by CTemplar are triggered on the desktop as they are with web browsers API. This can be done using Electron's session API, in `electron-main.ts` file.

**Comment by happyman125** [comment]
@The-Hidden-Hand So we want notification in electron app like webclient?
If so, I think we should send notification details from angular to electron. right?

**Comment by The-Hidden-Hand** [comment]
@happyman125 
Yes, we need to support "desktop notifications" in all our Electron apps.
Related: https://www.electronjs.org/docs/tutorial/notifications
