### ISSUE TITLE
Older browsers like IE doesn't display the expected 'unsupported' notification

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#957]
### Description

When using a browser that doesn't support window.crypto then the no content is loaded (as expected). However the alert() dialog displaying the error message is never displayed, leaving the user with just a blank page. This is caused by a syntax error in browser-compatibility.js, on line 12 there is a trailing , within the alert statement. Most modern browser are able to execute the code as desired despite the mistake, however older browsers such as IE does not do so, and coincidentally it is only these browsers which need to show this message.

Also, did you mean to write ' quotes around undefined? This part, 'undefined' == typeof window will always be false at this point, since the false branch of the condition '!window' at line 3 has been taken. This file is written in a very convoluted way making it hard to read and spot issues like this.

Having a linting process will avoid errors like these. I would also suggest having a more descriptive error message here to aid the user, and avoiding the use of window.alert(); for accessibility and UX reasons.

**Comment by superdev0714** [comment]
This task can be separated with below tasks

- [ ] Fix errors on `browser-compatibility.js`
- [ ] Add feature to check IE, Edge
Currently only checking compatible with `crypto`, should set the restriction IE, Edge
- [ ] Remove `alert()` and add the user friendly UI
- [ ] Cookie enable notification, if it's not enabled
Currently we are using `alert()` for this as well
- [ ] Linting with ESLint & Prettier

**Comment by The-Hidden-Hand** [comment]
@superdev0714 
>  Cookie enable notification, if it's not enabled
Actually it displays the alert all the times, even when cookies are enabled.
Could you submit a patch so I don't have to revert back and lose the code?
