### ISSUE TITLE
UI for Autocrypt, Inline PGP, and PGP/MIME

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#971]
### Expected behavior

- [x] Autocrypt: Allow enabling or disabling Autocrypt by mailbox and rely on the new API endpoints.
- [x] Inline PGP: Support for bodies with inline PGP messages using recipient's public keys.
- [x] PGP/MIME: Support for messages coming in such format.

Task recapitulation:

> Incoming Mail:
> 1. Check if autocrypt header is present.
> 2. If present then parse the autocrypt header.
> 3. Add sender in contacts (we are already doing so based on save_contacts setting)
> 4. If we are saving contact, at that time check if autocrypt header is valid parse it and save the public_key of remote user
> 5. Update last seen and autocrypt_timestamp as well
> 
> Outgoing Mail:
> 1. Check if mailbox have autocrypt enabled.
> 2. If enabled then check for contact if have the the public_key and autocrypt_timestamp is younger or equal to last_seen then we can include this remote user in autocrypt otherwise plain email
> 3. If remote user can be included then send the encrypted mail using controlled user and remote user public key and associate autocrypt header
> 4. if remote user cant be included then send the plain email but associate the autocrypt header with controlled user's data
> 
> For multiple recipient we will also include multiple Autocrypt-Gossip Header per recipient so that other users can also have access to public keys.

**Comment by mrusme** [comment]
+1 can't wait for this!

**Comment by mrusme** [comment]
Ou yeah! @The-Hidden-Hand is this now available on ctemplar.com?

**Comment by The-Hidden-Hand** [comment]
Yes @mrusme 

Also, you can now generate and make ECC keys as default for all your existing mailboxes, so you can get speed improvements too.

**Comment by mrusme** [comment]
@The-Hidden-Hand that is awesome, will try it! 👍🏼  Saw you also merged other feature requests / bugs – thank you for the super-quick iterations, great work!
