### ISSUE TITLE
Support custom *subdomain* for email and not just custom top level domain

### ISSUE THREAD

**Issue by Intensity** [CTemplar/webclient#974]
I notice that custom domains are possible in CTemplar, and yet naming a custom subdomain during the setup process results in an error message requesting that a valid domain be provided. Rather than registering "domain.com" I'd rather keep all other top-level records alone and register "mail.domain.com" or "mail.prod.domain.com".

Some other providers, such as ProtonMail aand FastMail, are able to accept the registration of a subdomain. The DNS records necessary for this are the same; only in this case, the subdomain is added to the record. In short, it's possible with those other providers, and with CTemplar it raises an error message.

I'm not sure if additional plumbing is necessary to test or support this on the backend, although it looks like provisionally that the front end rejects the attempt.

**Comment by The-Hidden-Hand** [comment]
Thanks for your input.

This has been enabled in our development branch and it will be released to public in the coming days.
