### ISSUE TITLE
Enforce 'noreferrer noopener' in all external links

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#976]
### Description

Links to cross-origin destinations are unsafe, (for example in index.html). Don't use target="_blank" without rel="noreferrer noopener". In older browsers, the page being linked to will be able to access the window object (using the window.opener property), giving access to data associated, and it may also allow the other page to redirect your page to a malicious URL.

**Comment by The-Hidden-Hand** [comment]
@happyman125 
It doesn't work for me. You can check with Github emails for example.

**Comment by happyman125** [comment]
@The-Hidden-Hand could you explain details? What doesn't work?

**Comment by The-Hidden-Hand** [comment]
@happyman125 
The links don't have `rel` attribute defined at all. Does it work for you?

**Comment by happyman125** [comment]
@The-Hidden-Hand Sorry, which links do you mean for example?

**Comment by The-Hidden-Hand** [comment]
@happyman125 
Any. Like those coming from Github emails, all of them have target blank but not the required rel.

**Comment by happyman125** [comment]
@The-Hidden-Hand could you provide any screenshot, code snippet or video?

**Comment by The-Hidden-Hand** [comment]
@happyman125 
I don't understand the question. Incoming emails are sanitized from dangerous tags, and there is an option to disable loading external resources (like images) so the users' IPs aren't revealed to the remote host. Besides this, external links must meet the requirements. Is that possible?

**Comment by happyman125** [comment]
@The-Hidden-Hand I think above code(safe: 'sanitize':disableExternalImages) is just for safe for external links included in message. In my memory, I remember there was a task that displays confirm message when user click external link in message like "Do you believe this link is not dangerous"? or something but I don't remember correctly.

If I am wrong, I will delete above code then it will meet requirements.

**Comment by The-Hidden-Hand** [comment]
@happyman125 
I think not done yet. Take a look: CTemplar/webclient#948

**Comment by The-Hidden-Hand** [comment]
Testing: https://github.com/CTemplar/webclient/pull/1071

**Comment by ckorder** [comment]
#1078 sorry for the duplicate, i just checked the ahref in the browser and saw it wasn't implemented. great job, I hope it will be default soon and find its way also into the android app.
