### ISSUE TITLE
Improve null checks and code strong typing

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#978]
### Description

Most null pointer issues just result in general reliability issues, but if an attacker can intentionally trigger a null pointer dereference, they may be able to use the resulting exception to bypass security logic or to cause the application to reveal debugging information that will be valuable in planning subsequent attacks.

In some places, else if statments are either not correctly using null check, or are in the wrong order. In `compose-mail.component.ts`, for example- `else if (this.selectedMailbox.signature) {...} (line 1304)` comes before` else if (this.selectedMailbox) {...} (line 1310)`, so the null check on the `selectedMailbox` property is effectively happening before you are using it. And in `mail.redusers.ts`, the `<any>new Date(previous_updated)` takes a parameter that is defined as: `const previous_updated = previous.updated || null`, meaning that `null` could be passed to `Date()` which would not be valid (it expected either/ only a number or string value). Another example, in compose-mail.component.ts where the null check happens after the variable is already used - line 108 contains `if (value) {...}`, but above on line 103 you've used `if (value.url) {...}`.

CTemplar uses TypeScript, but it not making use of it's static type checking features. Again, this is less of a security issue, and more of a software stability and code quality problem. There are literally hundreds of instances of any and none of them are necessary (e.g. in `mail-detail.component.ts`). Consider enabling `noImplicitAny` in your `tsconfig.json` and enforcing it before code can be committed.

**Comment by happyman125** [comment]
@The-Hidden-Hand so you want me to refactor similar issues all over the project or only want to add typescript checking before commit for changed files from now?

**Comment by The-Hidden-Hand** [comment]
@happyman125 
We'll have to review typings everywhere if we want to have a solid codebase. There are probably many places for change, so we'll have to do it in a few iterations but not for all the week. Please submit yesterday and today for review.

**Comment by The-Hidden-Hand** [comment]
There are many types not properly defined in the first iteration. Modals should be `NgbModalRef`, and so on.

**Comment by The-Hidden-Hand** [comment]
@CTemplar/front-end Here is a list:
https://deepsource.io/gh/CTemplar/webclient/issue/JS-0323/occurrences

**Comment by The-Hidden-Hand** [comment]
@rock-ejin 
I believe creating interfaces matching Django models would prevent a lot of bugs.
