### ISSUE TITLE
Disable autocomplete on all input fields

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#984]
### Description

In some cases autocomplete is not disabled, for example on the login screen autocomplete is not disabled for the form that accepts user credentials in users-sign-in.component.html.

It is especially important to disable autocomplete on login forms. If a cross-site scripting vector is present in the login page, a malicious actor could easily use a simple payload to send a CTemplars users saved login credentials to their site.

You can easily fix this, by specifying the autocomplete attribute to off, e.g. `<form method="post" action="/form" autocomplete="off">` or `<input type="text" id="cc" name="cc" autocomplete="off">`.

**Comment by happyman125** [comment]
@The-Hidden-Hand You mean only login form or other input fields as well?

**Comment by The-Hidden-Hand** [comment]
@happyman125 
This comes from Lissy93 report. She was asking to disable it on all input fields.

**Comment by happyman125** [comment]
Disable on login form is very sensitive for our users so we should decide seriously I think.

**Comment by happyman125** [comment]
@The-Hidden-Hand I need your thought about login form disable

**Comment by The-Hidden-Hand** [comment]
Security or convenience, I don't really have an answer.

**Comment by The-Hidden-Hand** [comment]
@happyman125 
I think we won't disable it because it is opt-in, so users can choose to not store the credentials for preventing this.
