### ISSUE TITLE
'Go back' action doesn't load previous email

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#995]
### Your environment

Firefox on Linux.

### Steps to reproduce

1. Open an email.
2. Go to a folder.
3. Go back to the email using the browser button.

### Expected behavior

The email would be displayed.

### Actual behavior

The email never loads and is always blank.

**Comment by happyman125** [comment]
@The-Hidden-Hand Can you confirm again? I just checked on firefox but it seems good

**Comment by The-Hidden-Hand** [comment]
@happyman125 
Strange, it works well now for me :thinking:
